import express, { Router, type IRouter, type Request, type Response } from "express";
import { getSupabaseConfig } from "../lib/supabase-env";

type SupabaseUser={id:string;email?:string|null;user_metadata?:Record<string,unknown>|null};
type AuthPayload={access_token?:string;refresh_token?:string;user?:SupabaseUser|null};
type AuthSessionPayload={access_token:string;refresh_token:string;user:SupabaseUser};
type AuthProviderPayload=AuthPayload&{error?:string;error_description?:string;msg?:string};
type ProviderError={status:number;code?:string;message:string;details?:string;hint?:string};
type SessionUser=SupabaseUser&{profile?:{id?:string;full_name?:string|null;username?:string|null;avatar_url?:string|null;bio?:string|null;department?:string|null;course?:string|null}|null};
const router:IRouter=Router(); const ACCESS_COOKIE="skillhub_access_token"; const REFRESH_COOKIE="skillhub_refresh_token";
const cookieOptions={httpOnly:true,signed:true,sameSite:"lax" as const,secure:process.env.NODE_ENV==="production",path:"/"};
async function supabaseRequest(path:string,init:{method?:string;headers?:Record<string,string>;body?:unknown}={}){const {url,anonKey,serviceRoleKey}=getSupabaseConfig();const apiKey=anonKey??serviceRoleKey;if(!apiKey)throw new Error("Missing Supabase API key");const headers:Record<string,string>={apikey:apiKey,"Content-Type":"application/json",...init.headers};return fetch(`${url}${path}`,{method:init.method??"GET",headers,body:init.body===undefined?undefined:typeof init.body==="string"?init.body:JSON.stringify(init.body)})}
async function readJson<T>(response:{text():Promise<string>}):Promise<T|null>{const text=await response.text();if(!text)return null;try{return JSON.parse(text) as T}catch{return null}}
async function providerError(response:{status:number;text():Promise<string>},fallback:string):Promise<ProviderError>{const d=await readJson<{code?:string;message?:string;details?:string;hint?:string;error?:string;error_description?:string;msg?:string}>(response);return{status:response.status,code:d?.code,message:d?.message??d?.error_description??d?.error??d?.msg??fallback,details:d?.details,hint:d?.hint}}
function setSessionCookies(res:Response,p:AuthPayload){if(!p.access_token||!p.refresh_token)return;res.cookie(ACCESS_COOKIE,p.access_token,{...cookieOptions,maxAge:3600000});res.cookie(REFRESH_COOKIE,p.refresh_token,{...cookieOptions,maxAge:30*24*60*60*1000})}
function clearSessionCookies(res:Response){res.clearCookie(ACCESS_COOKIE,cookieOptions);res.clearCookie(REFRESH_COOKIE,cookieOptions)}
function getSessionTokens(req:Request){return{accessToken:req.signedCookies?.[ACCESS_COOKIE] as string|undefined,refreshToken:req.signedCookies?.[REFRESH_COOKIE] as string|undefined}}
function getFullName(user:SupabaseUser,requestedName?:string){const n=user.user_metadata?.["full_name"];if(requestedName?.trim())return requestedName.trim();if(typeof n==="string"&&n.trim())return n.trim();return user.email?.split("@")[0]??"OLANET member"}
async function ensureProfile(user:SupabaseUser,accessToken:string|undefined,requestedName?:string):Promise<ProviderError|null>{const attempts=accessToken?[accessToken,undefined]:[undefined];let last:ProviderError|null=null;for(const token of attempts){try{const headers:Record<string,string>={Prefer:"resolution=merge-duplicates,return=minimal"};if(token)headers.Authorization=`Bearer ${token}`;const r=await supabaseRequest("/rest/v1/profiles",{method:"POST",headers,body:{id:user.id,full_name:getFullName(user,requestedName)}});if(r.ok||r.status===409)return null;last=await providerError(r,"Unable to create your profile")}catch(e){last={status:502,message:e instanceof Error?e.message:"Unable to reach Supabase profiles"}}}return last}
async function getProfile(userId:string,accessToken:string){const r=await supabaseRequest(`/rest/v1/profiles?select=id,full_name,username,avatar_url,bio,department,course&id=eq.${encodeURIComponent(userId)}&limit=1`,{method:"GET",headers:{Authorization:`Bearer ${accessToken}`}});if(!r.ok)return null;const p=await readJson<SessionUser["profile"][]>(r);return p?.[0]??null}
async function getAuthenticatedSession(req:Request,res:Response){const{accessToken,refreshToken}=getSessionTokens(req);if(!accessToken&&!refreshToken){res.status(401).json({error:"Not authenticated"});return null}let user=accessToken?await getUserFromAccessToken(accessToken):null;let activeAccessToken=accessToken;if(!user&&refreshToken){const refreshed=await refreshSession(refreshToken);if(refreshed){setSessionCookies(res,refreshed);user=refreshed.user;activeAccessToken=refreshed.access_token}}if(!user||!activeAccessToken){clearSessionCookies(res);res.status(401).json({error:"Session expired"});return null}return{user,accessToken:activeAccessToken}}
type ProfileUpdate={username?:string|null;full_name?:string|null;bio?:string|null;avatar_url?:string|null;department?:string|null;course?:string|null};
async function updateProfileRecord(user:SupabaseUser,accessToken:string,updates:ProfileUpdate){const response=await supabaseRequest("/rest/v1/profiles?on_conflict=id",{method:"POST",headers:{Authorization:`Bearer ${accessToken}`,Prefer:"resolution=merge-duplicates,return=representation"},body:{id:user.id,...updates}});if(!response.ok)throw await providerError(response,"Unable to update your profile");const rows=await readJson<SessionUser["profile"][]>(response);return rows?.[0]??null}
async function getUserFromAccessToken(token:string){const r=await supabaseRequest("/auth/v1/user",{method:"GET",headers:{Authorization:`Bearer ${token}`}});return r.ok?await readJson<SupabaseUser>(r):null}
async function refreshSession(refreshToken:string):Promise<AuthSessionPayload|null>{const r=await supabaseRequest("/auth/v1/token?grant_type=refresh_token",{method:"POST",body:{refresh_token:refreshToken}});return r.ok?await readJson<AuthSessionPayload>(r):null}

router.get("/auth/session",async(req,res)=>{try{const s=await getAuthenticatedSession(req,res);if(!s)return;const profile=await getProfile(s.user.id,s.accessToken);res.json({user:{...s.user,profile}})}catch(e){console.error("auth/session",e);res.status(500).json({error:"Unable to check your session"})}});
router.post("/auth/login",async(req,res)=>{try{const email=String(req.body?.email??"").trim().toLowerCase(),password=String(req.body?.password??"");if(!email||!password){res.status(400).json({error:"Email and password are required"});return}const r=await supabaseRequest("/auth/v1/token?grant_type=password",{method:"POST",body:{email,password}});const d=await readJson<AuthProviderPayload>(r);if(!r.ok||!d?.access_token){const e=await providerError(r,"Invalid email or password");res.status(e.status).json({error:e.message});return}setSessionCookies(res,d);const profileError=await ensureProfile(d.user!,d.access_token);res.json({user:{...d.user,profile:await getProfile(d.user!.id,d.access_token)},profileError});}catch(e){console.error("auth/login",e);res.status(500).json({error:e instanceof Error?e.message:"Unable to connect to authentication service"})}});
router.post("/auth/signup",async(req,res)=>{try{const email=String(req.body?.email??"").trim().toLowerCase(),password=String(req.body?.password??""),fullName=String(req.body?.fullName??"").trim();if(fullName.length<2||!email||password.length<6){res.status(400).json({error:"Name, valid email and a password of at least 6 characters are required"});return}const r=await supabaseRequest("/auth/v1/signup",{method:"POST",body:{email,password,data:{full_name:fullName}}});const d=await readJson<AuthProviderPayload>(r);if(!r.ok||!d?.user){const e=await providerError(r,"Unable to create your account");res.status(e.status).json({error:e.message});return}if(d.access_token){setSessionCookies(res,d);const profileError=await ensureProfile(d.user,d.access_token,fullName);res.json({user:{...d.user,profile:await getProfile(d.user.id,d.access_token)},profileError,needsEmailConfirmation:false});return}res.json({user:null,needsEmailConfirmation:true});}catch(e){console.error("auth/signup",e);res.status(500).json({error:e instanceof Error?e.message:"Unable to create your account"})}});
router.post("/auth/logout",async(req,res)=>{const{accessToken}=getSessionTokens(req);if(accessToken){await supabaseRequest("/auth/v1/logout",{method:"POST",headers:{Authorization:`Bearer ${accessToken}`}}).catch(()=>undefined)}clearSessionCookies(res);res.json({ok:true})});
router.post("/auth/verify-email",async(req,res)=>{try{const email=String(req.body?.email??"").trim().toLowerCase(),token=String(req.body?.token??"");if(!email||!token){res.status(400).json({error:"Email and verification code are required"});return}const r=await supabaseRequest("/auth/v1/verify",{method:"POST",body:{type:"email",email,token}});const d=await readJson<AuthProviderPayload>(r);if(!r.ok||!d?.access_token||!d.user){const e=await providerError(r,"That verification code is invalid or expired");res.status(e.status).json({error:e.message});return}setSessionCookies(res,d);const profileError=await ensureProfile(d.user,d.access_token);res.json({user:{...d.user,profile:await getProfile(d.user.id,d.access_token)},verified:true,profileError});}catch(e){console.error("auth/verify-email",e);res.status(500).json({error:e instanceof Error?e.message:"Unable to verify your email"})}});
router.post("/auth/resend-email",async(req,res)=>{try{const email=String(req.body?.email??"").trim().toLowerCase();if(!email){res.status(400).json({error:"Email is required"});return}const r=await supabaseRequest("/auth/v1/resend",{method:"POST",body:{type:"signup",email}});if(!r.ok){const e=await providerError(r,"Unable to resend the verification code");res.status(e.status).json({error:e.message});return}res.json({ok:true})}catch(e){console.error("auth/resend-email",e);res.status(500).json({error:e instanceof Error?e.message:"Unable to resend the verification code"})}});
router.put("/profile/me",async(req,res)=>{const s=await getAuthenticatedSession(req,res);if(!s)return;try{const p=await updateProfileRecord(s.user,s.accessToken,req.body??{});res.json({profile:p})}catch(e){const x=e as ProviderError;res.status(x.status||500).json({error:x.message||"Unable to update your profile"})}});
router.post("/profile/avatar",express.raw({type:/^image\//,limit:"8mb"}),async(req,res)=>{const s=await getAuthenticatedSession(req,res);if(!s)return;const contentType=req.headers["content-type"]||"image/jpeg";const path=`/storage/v1/object/profile-avatars/${s.user.id}`;const upload=await supabaseRequest(path,{method:"POST",headers:{Authorization:`Bearer ${s.accessToken}`,"Content-Type":contentType,upsert:"true"},body:req.body});if(!upload.ok){const e=await providerError(upload,"Unable to upload your profile picture");res.status(e.status).json({error:e.message});return}const base=process.env.SUPABASE_URL;const avatarUrl=base?`${base}/storage/v1/object/public/profile-avatars/${s.user.id}`:null;const p=await updateProfileRecord(s.user,s.accessToken,{avatar_url:avatarUrl});res.json({profile:p})});

export default router;
