import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import olanetAIRouter from "./olanet-ai-v2";
import supportAIRouter from "./support-ai";
import circlesRouter from "./circles";
import circlePostsRouter from "./circle-posts";
import feedRouter from "./feed";
import socialRouter from "./social";
import messagesRouter from "./messages";
import settingsRouter from "./settings";
import friendsRouter from "./friends";
import profileRouter from "./profile";
import notificationsRouter from "./notifications";

const router: IRouter = Router();
router.use(healthRouter);
router.use(authRouter);
router.use(olanetAIRouter);
router.use(supportAIRouter);
router.use(circlesRouter);
router.use(circlePostsRouter);
router.use(feedRouter);
router.use(socialRouter);
router.use("/messages", messagesRouter);
router.use(settingsRouter);
router.use(friendsRouter);
router.use(profileRouter);
router.use(notificationsRouter);
export default router;
