import { Router, type IRouter, type Request, type Response } from "express";
import { ReplitConnectors } from "@replit/connectors-sdk";

const router: IRouter = Router();
const ACCESS_COOKIE = "skillhub_access_token";
type User = { id: string; email?: string | null };
async function readJson<T>(response: { text(): Promise<string> }): Promise<T | null> { const text = await response.text(); try { return text ? JSON.parse(text) as T : null; } catch { return null; } }
async function supabase(path: string, token: string, init: { method?: string; body?: unknown; headers?: Record<string,string> } = {}) { const connectors = new ReplitConnectors(); return connectors.proxy("supabase", path, { ...init, headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}`, ...(init.headers || {}) } }); }
async function auth(req: Request, res: Response): Promise<{ user: User; token: string } | null> { const token = req.signedCookies?.[ACCESS_COOKIE] as string | undefined; if (!token) { res.status(401).json({ error: "Not authenticated" }); return null; } const r = await supabase("/auth/v1/user", token, { method: "GET" }); const user = await readJson<User>(r); if (!r.ok || !user?.id) { res.status(401).json({ error: "Session expired. Please log in again." }); return null; } return { user, token }; }
const json = (value: unknown) => JSON.stringify(value);
router.get("/notifications", async (req, res): Promise<void> => { const a = await auth(req, res); if (!a) return; const limit = Math.min(Math.max(Number(req.query.limit) || 30, 1), 100); const r = await supabase(`/rest/v1/notifications?user_id=eq.${a.user.id}&select=id,user_id,actor_id,type,title,body,entity_id,read_at,created_at&order=created_at.desc&limit=${limit}`, a.token, { method: "GET" }); const rows = await readJson<Array<Record<string,unknown>>>(r) ?? []; if (!r.ok) { res.status(r.status).json(rows); return; } const actorIds = [...new Set(rows.map(x => typeof x.actor_id === "string" ? x.actor_id : "").filter(Boolean))]; let actors: Array<Record<string,unknown>> = []; if (actorIds.length) { const p = await supabase(`/rest/v1/profiles?id=in.(${actorIds.map(encodeURIComponent).join(",")})&select=id,full_name,username,avatar_url`, a.token, { method: "GET" }); actors = await readJson<Array<Record<string,unknown>>>(p) ?? []; } const byId = new Map(actors.map(x => [String(x.id), x])); res.json(rows.map(n => ({ ...n, actor: n.actor_id ? byId.get(String(n.actor_id)) ?? null : null }))); });
router.patch("/notifications/:id/read", async (req, res): Promise<void> => { const a = await auth(req, res); if (!a) return; const r = await supabase(`/rest/v1/notifications?id=eq.${encodeURIComponent(req.params.id)}&user_id=eq.${a.user.id}`, a.token, { method: "PATCH", body: json({ read_at: new Date().toISOString() }), headers: { Prefer: "return=representation" } }); const data = await readJson<unknown>(r); res.status(r.ok ? 200 : r.status).json(data ?? {}); });
router.post("/notifications/read-all", async (req, res): Promise<void> => { const a = await auth(req, res); if (!a) return; const r = await supabase(`/rest/v1/notifications?user_id=eq.${a.user.id}&read_at=is.null`, a.token, { method: "PATCH", body: json({ read_at: new Date().toISOString() }), headers: { Prefer: "return=representation" } }); const data = await readJson<unknown>(r); res.status(r.ok ? 200 : r.status).json(data ?? {}); });
export default router;
