import { Router, type IRouter, type Request, type Response } from "express";
import { ReplitConnectors } from "@replit/connectors-sdk";

const router: IRouter = Router();
const ACCESS_COOKIE = "skillhub_access_token";
type User = { id: string; email?: string | null };
async function readJson<T>(response: { text(): Promise<string> }): Promise<T | null> { const text = await response.text(); try { return text ? JSON.parse(text) as T : null; } catch { return null; } }
async function supabase(path: string, token: string, init: { method?: string; body?: unknown; headers?: Record<string,string> } = {}) { const connectors = new ReplitConnectors(); return connectors.proxy("supabase", path, { ...init, headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}`, ...(init.headers || {}) } }); }
async function auth(req: Request, res: Response): Promise<{user:User;token:string}|null> { const token=req.signedCookies?.[ACCESS_COOKIE] as string|undefined; if(!token){res.status(401).json({error:"Not authenticated"});return null;} const r=await supabase("/auth/v1/user",token,{method:"GET"}); const user=await readJson<User>(r); if(!r.ok||!user?.id){res.status(401).json({error:"Session expired. Please log in again."});return null;} return {user,token}; }

router.patch("/settings/account", async (req,res):Promise<void>=>{ const session=await auth(req,res); if(!session)return; const body:Record<string,unknown>={}; if(typeof req.body?.email === "string" && req.body.email.trim()) body.email=req.body.email.trim(); if(typeof req.body?.password === "string" && req.body.password.length>=8) body.password=req.body.password; if(!Object.keys(body).length){res.status(400).json({error:"Provide a new email or a password of at least 8 characters."});return;} const r=await supabase("/auth/v1/user",session.token,{method:"PUT",body:JSON.stringify(body)}); const data=await readJson<Record<string,unknown>>(r); if(!r.ok){res.status(r.status).json({error:String(data?.msg||data?.message||data?.error_description||"Unable to update account settings.")});return;} res.json({ok:true,user:data}); });

router.post("/messages/:id/view-once", async(req,res):Promise<void>=>{ const session=await auth(req,res); if(!session)return; const messageId=Number(req.params.id); if(!Number.isInteger(messageId)){res.status(400).json({error:"Invalid message id"});return;} const check=await supabase(`/rest/v1/chat_messages?id=eq.${messageId}&select=id,conversation_id,group_id,sender_id,is_view_once&limit=1`,session.token,{method:"GET"}); const rows=await readJson<Array<{id:number;conversation_id:number|null;group_id:number|null;sender_id:string;is_view_once:boolean}>>(check); const message=rows?.[0]; if(!check.ok||!message){res.status(404).json({error:"Message not found"});return;} if(!message.is_view_once){res.status(400).json({error:"This message is not view-once."});return;} if(message.sender_id===session.user.id){res.status(400).json({error:"The sender cannot consume their own view-once message."});return;} const prior=await supabase(`/rest/v1/chat_message_views?message_id=eq.${messageId}&user_id=eq.${session.user.id}&select=message_id&limit=1`,session.token,{method:"GET"}); const priorRows=await readJson<unknown[]>(prior)??[]; if(priorRows.length){res.status(409).json({error:"This view-once message has already been opened."});return;} const write=await supabase("/rest/v1/chat_message_views",session.token,{method:"POST",body:JSON.stringify({message_id:messageId,user_id:session.user.id}),headers:{Prefer:"return=minimal"}}); if(!write.ok){res.status(403).json({error:"You cannot open this message."});return;} res.json({ok:true,consumed:true}); });

export default router;
