import { Router, type IRouter, type Request, type Response } from "express";
import { ReplitConnectors } from "@replit/connectors-sdk";

const router: IRouter = Router();
const ACCESS_COOKIE = "skillhub_access_token";
type User = { id: string; email?: string | null };
async function readJson<T>(response: { text(): Promise<string> }): Promise<T | null> { const text = await response.text(); try { return text ? JSON.parse(text) as T : null; } catch { return null; } }
async function supabase(path: string, token: string, init: { method?: string; body?: unknown; headers?: Record<string,string> } = {}) { const connectors = new ReplitConnectors(); return connectors.proxy("supabase", path, { ...init, headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}`, ...(init.headers || {}) } }); }
async function auth(req: Request, res: Response): Promise<{ user: User; token: string } | null> { const token = req.signedCookies?.[ACCESS_COOKIE] as string | undefined; if (!token) { res.status(401).json({ error: "Not authenticated" }); return null; } const r = await supabase("/auth/v1/user", token, { method: "GET" }); const user = await readJson<User>(r); if (!r.ok || !user?.id) { res.status(401).json({ error: "Session expired. Please log in again." }); return null; } return { user, token }; }
const pairFilter = (a: string, b: string) => `or=(and(requester_id.eq.${encodeURIComponent(a)},addressee_id.eq.${encodeURIComponent(b)}),and(requester_id.eq.${encodeURIComponent(b)},addressee_id.eq.${encodeURIComponent(a)}))`;

// Search separately by name and username. PostgREST's encoded OR filter was returning 400
// through the Vercel/Replit proxy, so two simple filters are merged safely here.
router.get("/people", async (req,res):Promise<void> => { const a=await auth(req,res); if(!a)return; const q=typeof req.query.q==="string"?req.query.q.trim():""; const base="select=id,full_name,username,avatar_url,bio&order=full_name.asc&limit=100"; const requests=q?[supabase(`/rest/v1/profiles?${base}&full_name=ilike.*${encodeURIComponent(q)}*`,a.token,{method:"GET"}),supabase(`/rest/v1/profiles?${base}&username=ilike.*${encodeURIComponent(q)}*`,a.token,{method:"GET"})]:[supabase(`/rest/v1/profiles?${base}`,a.token,{method:"GET"})]; const responses=await Promise.all(requests); const rows=(await Promise.all(responses.map(r=>readJson<Array<Record<string,unknown>>>(r)))).flatMap(x=>Array.isArray(x)?x:[]); const seen=new Set<string>(); const result=rows.filter(p=>typeof p.id==="string"&&p.id!==a.user.id&&!seen.has(p.id as string)&&seen.add(p.id as string)); const failed=responses.find(r=>!r.ok); if(failed&&!rows.length){res.status(failed.status||502).json({error:"Could not search OLANET users right now."});return;} res.json(result); });

router.get("/friends", async(req,res):Promise<void>=>{const a=await auth(req,res);if(!a)return;const r=await supabase(`/rest/v1/friendships?${pairFilter(a.user.id,a.user.id)}&select=*`,a.token,{method:"GET"});res.status(r.status).json(await readJson<unknown>(r)??[]);});
router.get("/friends/status/:userId", async(req,res):Promise<void>=>{const a=await auth(req,res);if(!a)return;const other=req.params.userId;if(!other||other===a.user.id){res.status(400).json({error:"Invalid friend."});return;}const r=await supabase(`/rest/v1/friendships?${pairFilter(a.user.id,other)}&select=*`,a.token,{method:"GET"});const rows=await readJson<Array<{id:string;requester_id:string;addressee_id:string;status:string}>>(r)??[];const f=rows[0];if(!r.ok){res.status(r.status).json({error:"Could not load friendship status."});return;}if(!f){res.json({status:"none"});return;}res.json({status:f.status,requestId:f.id,incoming:f.addressee_id===a.user.id});});
router.post("/friends/request", async(req,res):Promise<void>=>{const a=await auth(req,res);if(!a)return;const other=typeof req.body?.addressee_id==="string"?req.body.addressee_id.trim():"";if(!other||other===a.user.id){res.status(400).json({error:"Select another OLANET user."});return;}const existing=await supabase(`/rest/v1/friendships?${pairFilter(a.user.id,other)}&select=*`,a.token,{method:"GET"});const rows=await readJson<Array<{id:string;requester_id:string;addressee_id:string;status:string}>>(existing)??[];if(!existing.ok){res.status(existing.status).json({error:"Could not check friendship status."});return;}if(rows[0]){const f=rows[0];if(f.status==="accepted"){res.json({status:"accepted",requestId:f.id});return;}if(f.status==="pending"&&f.addressee_id===a.user.id){const accepted=await supabase(`/rest/v1/friendships?id=eq.${encodeURIComponent(f.id)}`,a.token,{method:"PATCH",body:JSON.stringify({status:"accepted",updated_at:new Date().toISOString()}),headers:{Prefer:"return=representation"}});res.status(accepted.ok?200:accepted.status).json(await readJson<unknown>(accepted)??{status:accepted.ok?"accepted":"failed"});return;}res.json({status:f.status,requestId:f.id});return;}const created=await supabase("/rest/v1/friendships?select=*",a.token,{method:"POST",body:JSON.stringify({requester_id:a.user.id,addressee_id:other,status:"pending"}),headers:{Prefer:"return=representation"}});const data=await readJson<unknown>(created);if(!created.ok){res.status(created.status).json(data??{error:"Could not send friend request."});return;}res.status(201).json(Array.isArray(data)?data[0]:data);});
router.patch("/friends/:id", async(req,res):Promise<void>=>{const a=await auth(req,res);if(!a)return;const status=req.body?.status;if(!["accepted","declined","blocked"].includes(status)){res.status(400).json({error:"Invalid friendship status."});return;}const r=await supabase(`/rest/v1/friendships?id=eq.${encodeURIComponent(req.params.id)}&addressee_id=eq.${encodeURIComponent(a.user.id)}`,a.token,{method:"PATCH",body:JSON.stringify({status,updated_at:new Date().toISOString()}),headers:{Prefer:"return=representation"}});res.status(r.ok?200:r.status).json(await readJson<unknown>(r)??{});});

export default router;
