import{Router,type IRouter,type Request,type Response}from"express";import{getSupabaseConfig}from"../lib/supabase-env";
const router:IRouter=Router();const ACCESS_COOKIE="skillhub_access_token",REFRESH_COOKIE="skillhub_refresh_token";type User={id:string;email?:string|null};type Session={user:User;token:string};type SupabaseInit={method?:string;body?:unknown;headers?:Record<string,string>};
async function readJson<T>(response:{text():Promise<string>}):Promise<T|null>{const text=await response.text();try{return text?JSON.parse(text)as T:null}catch{return null}}
async function supabase(path:string,token?:string,init:SupabaseInit={}){const{url,anonKey,serviceRoleKey}=getSupabaseConfig();const apiKey=anonKey??serviceRoleKey;if(!apiKey)throw new Error("Missing Supabase API key");const headers:Record<string,string>={apikey:apiKey,"Content-Type":"application/json",...(init.headers||{})};if(token)headers.Authorization=`Bearer ${token}`;return fetch(`${url}${path}`,{method:init.method??"GET",headers,body:init.body===undefined?undefined:typeof init.body==="string"?init.body:JSON.stringify(init.body)})}
function setCookie(res:Response,name:string,value:string,maxAge:number){res.cookie(name,value,{httpOnly:true,sameSite:"lax",secure:process.env.NODE_ENV==="production",path:"/",maxAge})}
async function refresh(res:Response,refreshToken:string):Promise<Session|null>{const config=getSupabaseConfig();const r=await supabase("/auth/v1/token?grant_type=refresh_token",undefined,{method:"POST",body:{refresh_token:refreshToken},headers:{Authorization:`Bearer ${config.anonKey??config.serviceRoleKey}`}});const d=await readJson<{access_token?:string;refresh_token?:string;user?:User}>(r);if(!r.ok||!d?.access_token||!d.user)return null;setCookie(res,ACCESS_COOKIE,d.access_token,3600000);if(d.refresh_token)setCookie(res,REFRESH_COOKIE,d.refresh_token,2592000000);return{user:d.user,token:d.access_token}}
async function auth(req:Request,res:Response):Promise<Session|null>{const token=(req.cookies?.[ACCESS_COOKIE]??req.signedCookies?.[ACCESS_COOKIE])as string|undefined;const refreshToken=(req.cookies?.[REFRESH_COOKIE]??req.signedCookies?.[REFRESH_COOKIE])as string|undefined;if(!token&&!refreshToken){res.status(401).json({error:"Not authenticated. Please log in again."});return null}if(token){const r=await supabase("/auth/v1/user",token);const user=await readJson<User>(r);if(r.ok&&user?.id)return{user,token}}if(refreshToken){const renewed=await refresh(res,refreshToken);if(renewed)return renewed}res.status(401).json({error:"Session expired. Please log in again."});return null}
const pairFilter=(a:string,b:string)=>`or=(and(requester_id.eq.${encodeURIComponent(a)},addressee_id.eq.${encodeURIComponent(b)}),and(requester_id.eq.${encodeURIComponent(b)},addressee_id.eq.${encodeURIComponent(a)}))`;const involvedFilter=(id:string)=>`or=(requester_id.eq.${encodeURIComponent(id)},addressee_id.eq.${encodeURIComponent(id)})`;
router.get("/people",async(req,res):Promise<void>=>{const a=await auth(req,res);if(!a)return;try{const q=typeof req.query.q==="string"?req.query.q.trim():"";const params=new URLSearchParams();params.set("select","id,full_name,username,avatar_url,bio");params.set("limit","100");if(q){const safe=q.replace(/[%,]/g," ").trim().slice(0,80);if(safe)params.set("or",`(full_name.ilike.*${safe}*,username.ilike.*${safe}*)`)}const r=await supabase(`/rest/v1/profiles?${params.toString()}`,a.token);const data=await readJson<unknown>(r);if(!r.ok){res.status(r.status||502).json({error:"Could not search OLANET users right now.",details:data});return}const rows=Array.isArray(data)?data as Array<Record<string,unknown>>:[];const seen=new Set<string>();res.json(rows.filter(p=>typeof p.id==="string"&&p.id!==a.user.id&&!seen.has(p.id)&&seen.add(p.id)))}catch(error){req.log.error({error},"People search failed");res.status(502).json({error:"Could not search OLANET users right now."})}});
router.get("/friends",async(req,res):Promise<void>=>{const a=await auth(req,res);if(!a)return;const r=await supabase(`/rest/v1/friendships?${involvedFilter(a.user.id)}&select=*&order=updated_at.desc`,a.token);const data=await readJson<unknown>(r);res.status(r.ok?200:r.status).json(data??{error:"Could not load friends."})});
router.get("/friends/status/:userId",async(req,res):Promise<void=>{const a=await auth(req,res);if(!a)return;const other=req.params.userId;if(!other||other===a.user.id){res.status(400).json({error:"Invalid friend."});return}const r=await supabase(`/rest/v1/friendships?${pairFilter(a.user.id,other)}&select=*&limit=1`,a.token);const rows=await readJson<Array<{id:string;requester_id:string;addressee_id:string;status:string}>>(r)??[];if(!r.ok){res.status(r.status).json({error:"Could not load friendship status."});return}const f=rows[0];res.json(f?{status:f.status,requestId:f.id,incoming:f.addressee_id===a.user.id}:{status:"none"})});
router.post("/friends/request",async(req,res):Promise<void=>{const a=await auth(req,res);if(!a)return;const other=typeof req.body?.addressee_id==="string"?req.body.addressee_id.trim():"";if(!other||other===a.user.id){res.status(400).json({error:"Select another OLANET user."});return}const existing=await supabase(`/rest/v1/friendships?${pairFilter(a.user.id,other)}&select=*&limit=1`,a.token);const rows=await readJson<Array<{id:string;requester_id:string;addressee_id:string;status:string}>>(existing)??[];if(!existing.ok){res.status(existing.status).json({error:"Could not check friendship status."});return}const f=rows[0];if(f){if(f.status==="accepted")return void res.json({status:"accepted",requestId:f.id});if(f.status==="pending")return void res.json({status:"pending",requestId:f.id,incoming:f.addressee_id===a.user.id});}const created=await supabase("/rest/v1/friendships?select=*",a.token,{method:"POST",body:{requester_id:a.user.id,addressee_id:other,status:"pending"},headers:{Prefer:"return=representation"}});const data=await readJson<unknown>(created);if(!created.ok){res.status(created.status).json({error:"Could not send friend request. Please try again.",details:data});return}res.status(201).json({status:"pending",requestId:Array.isArray(data)?(data[0] as{id?:string})?.id:undefined})});
export default router;