import { Router, type IRouter, type Request, type Response } from "express";
import { getSupabaseConfig } from "../lib/supabase-env";

const router: IRouter = Router();
const ACCESS_COOKIE = "skillhub_access_token";
const REFRESH_COOKIE = "skillhub_refresh_token";
type User = { id: string; email?: string | null };
type Session = { user: User; token: string };
type SupabaseInit = { method?: string; body?: unknown; headers?: Record<string, string> };
async function readJson<T>(response: { text(): Promise<string> }): Promise<T | null> { const text = await response.text(); try { return text ? JSON.parse(text) as T : null; } catch { return null; } }
async function supabase(path: string, token?: string, init: SupabaseInit = {}) {
  const { url, anonKey, serviceRoleKey } = getSupabaseConfig();
  const apiKey = serviceRoleKey ?? anonKey;
  if (!apiKey) throw new Error("Missing Supabase API key");
  const headers: Record<string, string> = { apikey: apiKey, "Content-Type": "application/json", ...(init.headers || {}) };
  if (token && !serviceRoleKey) headers.Authorization = `Bearer ${token}`;
  return fetch(`${url}${path}`, { method: init.method ?? "GET", headers, body: init.body === undefined ? undefined : typeof init.body === "string" ? init.body : JSON.stringify(init.body) });
}
function setCookie(res: Response, name: string, value: string, maxAge: number) { res.cookie(name, value, { httpOnly: true, signed: true, sameSite: "lax", secure: process.env.NODE_ENV === "production", path: "/", maxAge }); }
async function refresh(res: Response, refreshToken: string): Promise<Session | null> { const r = await supabase("/auth/v1/token?grant_type=refresh_token", undefined, { method: "POST", body: { refresh_token: refreshToken }, headers: { Authorization: `Bearer ${getSupabaseConfig().anonKey ?? getSupabaseConfig().serviceRoleKey}` } }); const d = await readJson<{access_token?:string;refresh_token?:string;user?:User}>(r); if (!r.ok || !d?.access_token || !d.user) return null; setCookie(res, ACCESS_COOKIE, d.access_token, 3600000); if (d.refresh_token) setCookie(res, REFRESH_COOKIE, d.refresh_token, 30 * 24 * 60 * 60 * 1000); return { user: d.user, token: d.access_token }; }
async function auth(req: Request, res: Response): Promise<Session | null> { const token = req.signedCookies?.[ACCESS_COOKIE] as string | undefined; const refreshToken = req.signedCookies?.[REFRESH_COOKIE] as string | undefined; if (!token && !refreshToken) { res.status(401).json({ error: "Not authenticated" }); return null; } if (token) { const r = await supabase("/auth/v1/user", token, { method: "GET" }); const user = await readJson<User>(r); if (r.ok && user?.id) return { user, token }; } if (refreshToken) { const renewed = await refresh(res, refreshToken); if (renewed) return renewed; } res.status(401).json({ error: "Session expired. Please log in again." }); return null; }
const pairFilter = (a: string, b: string) => `or=(and(requester_id.eq.${encodeURIComponent(a)},addressee_id.eq.${encodeURIComponent(b)}),and(requester_id.eq.${encodeURIComponent(b)},addressee_id.eq.${encodeURIComponent(a)}))`;
const involvedFilter = (id: string) => `or=(requester_id.eq.${encodeURIComponent(id)},addressee_id.eq.${encodeURIComponent(id)})`;

router.get("/people", async (req,res):Promise<void> => { const a=await auth(req,res); if(!a)return; const q=typeof req.query.q==="string"?req.query.q.trim():""; const base="select=id,full_name,username,avatar_url,bio&limit=100"; const requests=q?[supabase(`/rest/v1/profiles?${base}&full_name=ilike.*${encodeURIComponent(q)}*`,a.token,{method:"GET"}),supabase(`/rest/v1/profiles?${base}&username=ilike.*${encodeURIComponent(q)}*`,a.token,{method:"GET"})]:[supabase(`/rest/v1/profiles?${base}`,a.token,{method:"GET"})]; const responses=await Promise.all(requests); const parsed=await Promise.all(responses.map(r=>readJson<Array<Record<string,unknown>>>(r))); const rows=parsed.flatMap(x=>Array.isArray(x)?x:[]); const seen=new Set<string>(); const result=rows.filter(p=>typeof p.id==="string"&&p.id!==a.user.id&&!seen.has(p.id as string)&&seen.add(p.id as string)); const failed=responses.find(r=>!r.ok); if(failed&&!rows.length){res.status(failed.status||502).json({error:"Could not search OLANET users right now."});return;} res.json(result); });
router.get("/friends", async(req,res):Promise<void>=>{const a=await auth(req,res);if(!a)return;const r=await supabase(`/rest/v1/friendships?${involvedFilter(a.user.id)}&select=*&order=updated_at.desc`,a.token,{method:"GET"});const data=await readJson<unknown>(r);res.status(r.ok?200:r.status).json(data??{error:"Could not load friends."});});
router.get("/friends/status/:userId", async(req,res):Promise<void>=>{const a=await auth(req,res);if(!a)return;const other=req.params.userId;if(!other||other===a.user.id){res.status(400).json({error:"Invalid friend."});return;}const r=await supabase(`/rest/v1/friendships?${pairFilter(a.user.id,other)}&select=*&limit=1`,a.token,{method:"GET"});const rows=await readJson<Array<{id:string;requester_id:string;addressee_id:string;status:string}>>(r)??[];if(!r.ok){res.status(r.status).json({error:"Could not load friendship status."});return;}const f=rows[0];if(!f){res.json({status:"none"});return;}res.json({status:f.status,requestId:f.id,incoming:f.addressee_id===a.user.id});});
router.post("/friends/request", async(req,res):Promise<void>=>{const a=await auth(req,res);if(!a)return;const other=typeof req.body?.addressee_id==="string"?req.body.addressee_id.trim():"";if(!other||other===a.user.id){res.status(400).json({error:"Select another OLANET user."});return;}
 const existing=await supabase(`/rest/v1/friendships?${pairFilter(a.user.id,other)}&select=*&limit=1`,a.token,{method:"GET"}); const rows=await readJson<Array<{id:string;requester_id:string;addressee_id:string;status:string}>>(existing)??[]; if(!existing.ok){res.status(existing.status).json({error:"Could not check friendship status."});return;}
 const f=rows[0]; if(f){ if(f.status==="accepted"){res.json({status:"accepted",requestId:f.id});return;} if(f.status==="pending"&&f.addressee_id===a.user.id){const accepted=await supabase(`/rest/v1/friendships?id=eq.${encodeURIComponent(f.id)}`,a.token,{method:"PATCH",body:{status:"accepted",updated_at:new Date().toISOString()},headers:{Prefer:"return=representation"}});const d=await readJson<unknown>(accepted);res.status(accepted.ok?200:accepted.status).json(accepted.ok?{status:"accepted",requestId:f.id,data:d}:d??{error:"Could not accept friend request."});return;} if((f.status==="declined"||f.status==="blocked")&&f.requester_id===a.user.id){const retried=await supabase(`/rest/v1/friendships?id=eq.${encodeURIComponent(f.id)}`,a.token,{method:"PATCH",body:{status:"pending",addressee_id:other,updated_at:new Date().toISOString()},headers:{Prefer:"return=representation"}});const d=await readJson<unknown>(retried);res.status(retried.ok?200:retried.status).json(retried.ok?{status:"pending",requestId:f.id}:d??{error:"Could not resend friend request."});return;} res.json({status:f.status,requestId:f.id,incoming:f.addressee_id===a.user.id});return; }
 const created=await supabase("/rest/v1/friendships?select=*",a.token,{method:"POST",body:{requester_id:a.user.id,addressee_id:other,status:"pending"},headers:{Prefer:"return=representation"}});const data=await readJson<unknown>(created);if(!created.ok){res.status(created.status).json({error:"Could not send friend request. Please try again.",details:data});return;}res.status(201).json({status:"pending",requestId:Array.isArray(data)?(data[0] as {id?:string})?.id:undefined}); });
router.patch("/friends/:id", async(req,res):Promise<void=>{const a=await auth(req,res);if(!a)return;const status=req.body?.status;if(!["accepted","declined","blocked"].includes(status)){res.status(400).json({error:"Invalid friendship status."});return;}const r=await supabase(`/rest/v1/friendships?id=eq.${encodeURIComponent(req.params.id)}&addressee_id=eq.${encodeURIComponent(a.user.id)}`,a.token,{method:"PATCH",body:{status,updated_at:new Date().toISOString()},headers:{Prefer:"return=representation"}});const d=await readJson<unknown>(r);res.status(r.ok?200:r.status).json(d??{error:r.ok?"":"Could not update friend request."});});
export default router;
