import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';
import { SocialHub } from '@/components/social-hub';
export type AuthUser = { id: string; email?: string | null; user_metadata?: Record<string, unknown> | null; profile?: { id?: string; full_name?: string | null; username?: string | null; avatar_url?: string | null; bio?: string | null; department?: string | null; course?: string | null; } | null; };
export type ProfileUpdateInput = { username?: string | null; full_name?: string | null; bio?: string | null; avatar_url?: string | null; department?: string | null; course?: string | null; };
type AuthResponse = { user?: AuthUser; error?: string; needsEmailConfirmation?: boolean; verified?: boolean; profileCreated?: boolean; profileError?: { status: number; code?: string; message: string; details?: string; hint?: string } | null; };
type AuthContextValue = { status: 'loading'|'authenticated'|'unauthenticated'; user: AuthUser|null; login:(email:string,password:string)=>Promise<AuthResponse>; signup:(fullName:string,email:string,password:string)=>Promise<AuthResponse>; logout:()=>Promise<void>; updateProfile:(updates:ProfileUpdateInput)=>Promise<NonNullable<AuthUser['profile']>>; uploadAvatar:(file:File)=>Promise<NonNullable<AuthUser['profile']>> };
const AuthContext=createContext<AuthContextValue|null>(null);
const authCooldowns=new Map<string,number>();
function enforceCooldown(key:string,seconds:number){const now=Date.now();const until=authCooldowns.get(key)??0;if(until>now)throw new Error(`Please wait ${Math.ceil((until-now)/1000)} seconds before trying again.`);authCooldowns.set(key,now+seconds*1000);}
async function request(path:string,init?:RequestInit){const response=await fetch(`/api/auth/${path}`,{...init,credentials:'include',headers:{'Content-Type':'application/json',...init?.headers}});const data=(await response.json().catch(()=>({}))) as AuthResponse;if(!response.ok){if(response.status===429||data.error?.toLowerCase().includes('over_email_send_rate_limit'))throw new Error('Email sending is temporarily rate-limited. Please wait a few minutes before trying again.');throw new Error(data.error??'Something went wrong. Please try again.');}return data;}
async function profileRequest(init:RequestInit){const response=await fetch('/api/profile',{...init,credentials:'include',headers:{'Content-Type':'application/json',...init?.headers}});const data=(await response.json().catch(()=>({}))) as AuthUser['profile'] & { error?: string };if(!response.ok)throw new Error(data.error??'Unable to update your profile.');if(!data?.id)throw new Error('Supabase returned no profile after saving.');return data as NonNullable<AuthUser['profile']>;}
function fileToDataUrl(file:File){return new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>{if(typeof reader.result==='string')resolve(reader.result);else reject(new Error('Unable to read image file.'));};reader.onerror=()=>reject(new Error('Unable to read image file.'));reader.readAsDataURL(file);});}
export function AuthProvider({children}:{children:ReactNode}){const [status,setStatus]=useState<AuthContextValue['status']>('loading');const [user,setUser]=useState<AuthUser|null>(null);useEffect(()=>{let active=true;request('session').then(data=>{if(!active)return;setUser(data.user??null);setStatus(data.user?'authenticated':'unauthenticated')}).catch(()=>{if(!active)return;setUser(null);setStatus('unauthenticated')});return()=>{active=false}},[]);const value=useMemo<AuthContextValue>(()=>({status,user,async login(email,password){const data=await request('login',{method:'POST',body:JSON.stringify({email,password})});setUser(data.user??null);setStatus('authenticated');return data;},async signup(fullName,email,password){const normalized=email.trim().toLowerCase();enforceCooldown(`signup:${normalized}`,15);const data=await request('signup',{method:'POST',body:JSON.stringify({fullName,email:normalized,password})});if(data.user&&!data.profileError){setUser(data.user);setStatus('authenticated')}return data;},async logout(){await request('logout',{method:'POST'}).catch(()=>undefined);setUser(null);setStatus('unauthenticated');},async updateProfile(updates){const profile=await profileRequest({method:'PATCH',body:JSON.stringify(updates)});setUser(current=>current?{...current,profile}:current);return profile;},async uploadAvatar(file){if(!/^image\/(jpeg|jpg|png|webp)$/.test(file.type))throw new Error('Avatar must be a JPG, PNG or WebP image.');const avatar_url=await fileToDataUrl(file);const profile=await profileRequest({method:'PATCH',body:JSON.stringify({avatar_url})});setUser(current=>current?{...current,profile}:current);return profile;}}),[status,user]);return <AuthContext.Provider value={value}>{children}{status==='authenticated'&&<SocialHub/>}</AuthContext.Provider>}
export function useAuth(){const context=useContext(AuthContext);if(!context)throw new Error('useAuth must be used within AuthProvider');return context;}
