import { createContext,useContext,useEffect,useMemo,useState,type ReactNode } from 'react';
export type AuthUser={id:string;email?:string|null;user_metadata?:Record<string,unknown>|null;profile?:{id?:string;full_name?:string|null;username?:string|null;avatar_url?:string|null;bio?:string|null;department?:string|null;course?:string|null}|null};
export type ProfileUpdateInput={username?:string|null;full_name?:string|null;bio?:string|null;avatar_url?:string|null;department?:string|null;course?:string|null};
type ProfileResponse={profile?:AuthUser['profile'];error?:string};type AuthResponse={user?:AuthUser;error?:string;needsEmailConfirmation?:boolean;verified?:boolean;profileCreated?:boolean;profileError?:{status:number;code?:string;message:string;details?:string;hint?:string}|null};
type AuthContextValue={status:'loading'|'authenticated'|'unauthenticated';user:AuthUser|null;login:(email:string,password:string)=>Promise<AuthResponse>;signup:(fullName:string,email:string,password:string)=>Promise<AuthResponse>;logout:()=>Promise<void>;updateProfile:(updates:ProfileUpdateInput)=>Promise<NonNullable<AuthUser['profile']>>;uploadAvatar:(file:File)=>Promise<NonNullable<AuthUser['profile']>>};
const AuthContext=createContext<AuthContextValue|null>(null);const authCooldowns=new Map<string,number>();
function enforceCooldown(key:string,seconds:number){const now=Date.now(),until=authCooldowns.get(key)??0;if(until>now)throw new Error(`Please wait ${Math.ceil((until-now)/1000)} seconds before trying again.`);authCooldowns.set(key,now+seconds*1000)}
async function request(path:string,init?:RequestInit){const r=await fetch(`/api/auth/${path}`,{...init,cache:'no-store',credentials:'include',headers:{'Cache-Control':'no-store','Content-Type':'application/json',...init?.headers}});const d=(await r.json().catch(()=>({}))) as AuthResponse;if(!r.ok)throw new Error(d.error??'Something went wrong. Please try again.');return d}
async function profileRequest(path:string,init?:RequestInit){const binary=init?.body instanceof Blob||init?.body instanceof ArrayBuffer;const r=await fetch(`/api/profile/${path}`,{...init,cache:'no-store',credentials:'include',headers:{'Cache-Control':'no-store',...(binary?{}:{'Content-Type':'application/json'}),...init?.headers}});const d=(await r.json().catch(()=>({}))) as ProfileResponse;if(!r.ok)throw new Error(d.error??'Unable to update your profile.');if(!d.profile)throw new Error('Supabase returned no profile after saving.');return d.profile}
function LoadingScreen(){return <div className="min-h-[100dvh] bg-[#f0f2f5]" aria-label="Loading OLANET"><div className="mx-auto flex min-h-[100dvh] max-w-6xl items-center justify-center p-6"><div className="w-full max-w-md"><div className="mb-6 h-10 w-32 animate-pulse rounded-lg bg-[#d8dee3]"/><div className="h-28 animate-pulse rounded-xl bg-white"/><div className="mt-4 grid grid-cols-3 gap-3"><div className="h-20 animate-pulse rounded-xl bg-white"/><div className="h-20 animate-pulse rounded-xl bg-white"/><div className="h-20 animate-pulse rounded-xl bg-white"/></div></div></div></div>}
export function AuthProvider({children}:{children:ReactNode}){const[status,setStatus]=useState<AuthContextValue['status']>('loading');const[user,setUser]=useState<AuthUser|null>(null);useEffect(()=>{let active=true;request('session').then(d=>{if(!active)return;setUser(d.user??null);setStatus(d.user?'authenticated':'unauthenticated')}).catch(()=>{if(active){setUser(null);setStatus('unauthenticated')}});return()=>{active=false}},[]);const value=useMemo<AuthContextValue>(()=>({status,user,async login(email,password){const d=await request('login',{method:'POST',body:JSON.stringify({email,password})});setUser(d.user??null);setStatus('authenticated');return d},async signup(fullName,email,password){const normalized=email.trim().toLowerCase();enforceCooldown(`signup:${normalized}`,15);const d=await request('signup',{method:'POST',body:JSON.stringify({fullName,email:normalized,password})});if(d.user&&!d.profileError){setUser(d.user);setStatus('authenticated')}return d},async logout(){await request('logout',{method:'POST'}).catch(()=>undefined);setUser(null);setStatus('unauthenticated')},async updateProfile(updates){const p=await profileRequest('me',{method:'PUT',body:JSON.stringify(updates)});setUser(c=>c?{...c,profile:p}:c);return p},async uploadAvatar(file){const p=await profileRequest('avatar',{method:'POST',headers:{'Content-Type':file.type},body:file});setUser(c=>c?{...c,profile:p}:c);return p}}),[status,user]);if(status==='loading')return <AuthContext.Provider value={value}><LoadingScreen/></AuthContext.Provider>;return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>}
export function useAuth(){const c=useContext(AuthContext);if(!c)throw new Error('useAuth must be used within AuthProvider');return c}
