const ACCESS_COOKIE="skillhub_access_token";
const REFRESH_COOKIE="skillhub_refresh_token";
function config(){const url=String(process.env.SUPABASE_URL||"").trim().replace(/\/$/,"");const key=String(process.env.SUPABASE_SERVICE_ROLE_KEY||process.env.SUPABASE_ANON_KEY||"").trim();if(!url||!key)throw new Error("Supabase environment is not configured");return{url,key};}
async function sb(path,options={}){const{url,key}=config();return fetch(`${url}${path}`,{...options,headers:{apikey:key,"Content-Type":"application/json",...(options.headers||{})}});}
async function json(r){const t=await r.text();if(!t)return null;try{return JSON.parse(t)}catch{return null}}
function cookies(req){const out={};for(const part of String(req.headers.cookie||"").split(";")){const i=part.indexOf("=");if(i>0)out[part.slice(0,i).trim()]=decodeURIComponent(part.slice(i+1).trim())}return out}
function setSession(res,d){res.setHeader("Set-Cookie",[`${ACCESS_COOKIE}=${encodeURIComponent(d.access_token)}; Path=/; HttpOnly; SameSite=Lax; Max-Age=3600; Secure`,`${REFRESH_COOKIE}=${encodeURIComponent(d.refresh_token)}; Path=/; HttpOnly; SameSite=Lax; Max-Age=2592000; Secure`])}
async function session(req,res){const c=cookies(req);let token=c[ACCESS_COOKIE],user=null;if(token){const r=await sb("/auth/v1/user",{headers:{Authorization:`Bearer ${token}`}});if(r.ok)user=await json(r)}if(!user&&c[REFRESH_COOKIE]){const r=await sb("/auth/v1/token?grant_type=refresh_token",{method:"POST",body:JSON.stringify({refresh_token:c[REFRESH_COOKIE]})});const d=await json(r);if(r.ok&&d?.access_token&&d?.user){token=d.access_token;user=d.user;setSession(res,d)}}if(!user?.id){res.status(401).json({error:"Not authenticated. Please log in again."});return null}return{user,token}}
async function member(req,res,s,id){const r=await sb(`/rest/v1/direct_conversation_members?conversation_id=eq.${encodeURIComponent(id)}&user_id=eq.${encodeURIComponent(s.user.id)}&select=conversation_id&limit=1`,{headers:{Authorization:`Bearer ${s.token}`}});const d=await json(r);if(!r.ok)return res.status(r.status).json({error:"Could not verify conversation access.",details:d});if(!Array.isArray(d)||!d.length){res.status(403).json({error:"You are not a member of this conversation."});return null}return true}
export default async function handler(req,res){try{const s=await session(req,res);if(!s)return;const id=String(req.query?.id||"").trim();if(!id||!/^\d+$/.test(id))return res.status(400).json({error:"Invalid conversation id."});if(!(await member(req,res,s,id)))return;
if(req.method==="GET"){const r=await sb(`/rest/v1/chat_messages?conversation_id=eq.${encodeURIComponent(id)}&select=*&order=created_at.desc&limit=100`,{headers:{Authorization:`Bearer ${s.token}`}});const d=await json(r);return res.status(r.status).json(Array.isArray(d)?d.reverse():d||[])}
if(req.method==="POST"){const body=typeof req.body?.body==="string"?req.body.body.trim():"";const mediaType=typeof req.body?.media_type==="string"?req.body.media_type.trim().toLowerCase():null;const mediaUrl=typeof req.body?.media_url==="string"?req.body.media_url.trim():null;const viewOnce=Boolean(req.body?.is_view_once);const allowed=["image","video","voice","video_note"];if(viewOnce&&(!mediaType||!allowed.includes(mediaType)||!mediaUrl))return res.status(400).json({error:"View Once is available only for pictures, videos, voice notes, and video notes."});if(mediaType&&!allowed.includes(mediaType))return res.status(400).json({error:"Unsupported media type."});if(mediaType&&!mediaUrl)return res.status(400).json({error:"A media URL is required when media type is provided."});if(!body&&!mediaUrl)return res.status(400).json({error:"Message or media is required."});const r=await sb("/rest/v1/chat_messages?select=*",{method:"POST",headers:{Authorization:`Bearer ${s.token}`,Prefer:"return=representation"},body:JSON.stringify({conversation_id:Number(id),sender_id:s.user.id,body,reply_to_id:req.body?.reply_to_id||null,is_view_once:viewOnce,media_type:mediaType,media_url:mediaUrl})});const d=await json(r);return res.status(r.ok?201:r.status).json(d||{error:"Message could not be sent."})}
return res.status(405).json({error:"Method not allowed."});}catch(e){return res.status(500).json({error:e?.message||"Direct message service failed."})}}
