import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Bot, Send, Users, X } from 'lucide-react';
import { CircleAiPanel } from '@/components/circle-ai-panel';

const circles: Record<string, string> = {
  electrical: 'Electrical Engineering', civil: 'Civil Engineering', mechanical: 'Mechanical Engineering', 'computer-science': 'Computer Science', 'phone-repair': 'Phone Repair', fashion: 'Fashion', carpentry: 'Carpentry', agriculture: 'Agriculture', catering: 'Catering',
};
type Group = { id: number; name: string; description?: string | null };
type Chat = { id: number; sender_id: string; body: string; created_at: string };
const api = async (path: string, init?: RequestInit) => { const r = await fetch(`/api${path}`, { ...init, credentials: 'include', headers: { 'Content-Type': 'application/json', ...(init?.headers || {}) } }); const data = await r.json().catch(() => null); if (!r.ok) throw new Error(data?.error || 'Request failed'); return data; };

export function CircleExperience() {
  const [path, setPath] = useState(() => window.location.pathname); const [ai, setAi] = useState(false); const [group, setGroup] = useState<Group | null>(null); const [joined, setJoined] = useState(false); const [chatOpen, setChatOpen] = useState(false); const [messages, setMessages] = useState<Chat[]>([]); const [text, setText] = useState(''); const [error, setError] = useState('');
  const slug = useMemo(() => path.match(/^\/circles\/([^/]+)/)?.[1] || '', [path]); const circleName = circles[slug];
  useEffect(() => { const refresh = () => setPath(window.location.pathname); window.addEventListener('popstate', refresh); const timer = window.setInterval(refresh, 300); return () => { window.removeEventListener('popstate', refresh); window.clearInterval(timer); }; }, []);
  useEffect(() => { setAi(false); setChatOpen(false); setGroup(null); setJoined(false); setMessages([]); setError(''); if (!circleName) return; void (async () => { try { const groups = await api(`/groups?q=${encodeURIComponent(circleName)}`) as Group[]; const exact = Array.isArray(groups) ? groups.find(g => g.name === circleName) : null; if (exact) setGroup(exact); } catch (e) { setError(e instanceof Error ? e.message : 'Could not load the circle group.'); } })(); }, [circleName]);
  const ensureGroup = async () => { if (group) return group; const groups = await api(`/groups?q=${encodeURIComponent(circleName)}`) as Group[]; const exact = Array.isArray(groups) ? groups.find(g => g.name === circleName) : null; if (exact) { setGroup(exact); return exact; } const created = await api('/groups', { method: 'POST', body: JSON.stringify({ name: circleName, description: `${circleName} OLANET group lobby` }) }); const next = Array.isArray(created) ? created[0] : created; setGroup(next); return next as Group; };
  const enterGroup = async () => { try { setError(''); const g = await ensureGroup(); await api(`/groups/${g.id}/join`, { method: 'POST' }).catch(e => { if (!String(e?.message || '').toLowerCase().includes('duplicate')) throw e; }); setJoined(true); setChatOpen(true); const data = await api(`/groups/${g.id}/messages`); setMessages(Array.isArray(data) ? data : []); } catch (e) { setError(e instanceof Error ? e.message : 'Could not enter this group.'); } };
  const loadMessages = async () => { if (!group) return; try { const data = await api(`/groups/${group.id}/messages`); setMessages(Array.isArray(data) ? data : []); } catch {} };
  useEffect(() => { if (!chatOpen || !group) return; const t = window.setInterval(() => void loadMessages(), 3000); return () => window.clearInterval(t); }, [chatOpen, group]);
  const send = async () => { if (!text.trim() || !group) return; try { const created = await api(`/groups/${group.id}/messages`, { method: 'POST', body: JSON.stringify({ body: text.trim() }) }); const item = Array.isArray(created) ? created[0] : created; setMessages(v => [...v, item]); setText(''); } catch (e) { setError(e instanceof Error ? e.message : 'Message could not be sent.'); } };
  if (!circleName) return null;
  return <>
    <div className="fixed bottom-20 right-4 z-[58] flex items-center gap-2 rounded-full bg-white p-1.5 shadow-xl ring-1 ring-[#e4e6eb] lg:bottom-5"><button onClick={() => setAi(true)} className="inline-flex items-center gap-2 rounded-full bg-[#1877f2] px-4 py-3 text-sm font-extrabold text-white"><Bot size={18}/> {circleName} AI</button><button onClick={() => void enterGroup()} className="inline-flex items-center gap-2 rounded-full bg-[#e4e6eb] px-4 py-3 text-sm font-extrabold text-[#1c1e21]"><Users size={18}/> {joined ? 'Open group' : 'Join group'}</button></div>
    {error && <div className="fixed bottom-36 right-4 z-[59] max-w-sm rounded-xl bg-[#fff0ed] px-4 py-3 text-xs font-bold text-[#a24f42] shadow-lg">{error}</div>}
    {ai && <div className="fixed inset-0 z-[80] overflow-y-auto bg-black/40 p-3 sm:p-8"><div className="mx-auto max-w-3xl"><div className="mb-2 flex justify-end"><button onClick={() => setAi(false)} className="rounded-full bg-white p-2 shadow"><X size={20}/></button></div><CircleAiPanel circleId={Object.keys(circles).indexOf(slug)+1} circleName={circleName}/></div></div>}
    {chatOpen && group && <div className="fixed inset-0 z-[85] bg-[#efeae2]"><div className="mx-auto flex h-full max-w-4xl flex-col bg-[#efeae2] shadow-2xl"><header className="flex shrink-0 items-center gap-3 bg-[#075e54] px-4 py-3 text-white"><button onClick={() => setChatOpen(false)} className="rounded-full p-2 hover:bg-white/10"><ArrowLeft size={20}/></button><div className="grid h-10 w-10 place-items-center rounded-full bg-white/20"><Users size={20}/></div><div className="min-w-0"><p className="truncate font-bold">{group.name}</p><p className="text-xs text-white/75">OLANET group · members chat here</p></div></header><div className="flex-1 space-y-2 overflow-y-auto p-4">{messages.map(m => <div key={m.id} className="max-w-[82%] rounded-xl rounded-tl-sm bg-white px-3 py-2 shadow-sm"><p className="whitespace-pre-wrap text-sm text-[#303030]">{m.body}</p><p className="mt-1 text-[10px] text-[#8a8a8a]">{new Date(m.created_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</p></div>)}{!messages.length && <div className="flex h-full items-center justify-center text-sm text-[#667781]">No messages yet. Start the circle conversation.</div>}</div><div className="flex shrink-0 gap-2 bg-[#f0f0f0] p-3"><input value={text} onChange={e => setText(e.target.value)} onKeyDown={e => { if (e.key === 'Enter') void send(); }} placeholder="Message the group" className="min-w-0 flex-1 rounded-full bg-white px-4 py-3 text-sm outline-none"/><button onClick={() => void send()} disabled={!text.trim()} className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-[#075e54] text-white disabled:opacity-50"><Send size={18}/></button></div></div></div>}
  </>;
}
