import { useEffect, useState } from 'react';
import { ArrowLeft, MessageCircle, Search, Send, UserPlus, Users, X } from 'lucide-react';
import { useAuth } from '@/lib/auth';

type Person={id:string;full_name?:string|null;username?:string|null;avatar_url?:string|null;bio?:string|null};
type Chat={id:number;sender_id:string;body:string;created_at:string};
type FriendState={status:'none'|'pending'|'accepted'|'declined'|'blocked';incoming?:boolean;requestId?:string};
const api=(path:string,init?:RequestInit)=>fetch(`/api${path}`,{...init,credentials:'include',headers:{'Content-Type':'application/json',...(init?.headers||{})}}).then(async r=>{const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.error||'Request failed');return d;});

export function DirectMessageHub(){
 const{user}=useAuth();const[open,setOpen]=useState(()=>window.location.pathname==='/messages');const[people,setPeople]=useState<Person[]>([]);const[query,setQuery]=useState('');const[selected,setSelected]=useState<Person|null>(null);const[conversation,setConversation]=useState<number|null>(null);const[messages,setMessages]=useState<Chat[]>([]);const[text,setText]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[friendStates,setFriendStates]=useState<Record<string,FriendState>>({});
 const loadPeople=async(q='')=>{try{setError('');const r=await api(`/people${q.trim()?`?q=${encodeURIComponent(q.trim())}`:''}`);setPeople(Array.isArray(r)?r:[]);}catch(e){setError(e instanceof Error?e.message:'Could not find users.');}};
 const loadMessages=async(id:number)=>{try{const r=await api(`/conversations/${id}/messages`);setMessages(Array.isArray(r)?r:[]);}catch(e){setError(e instanceof Error?e.message:'Could not load messages.');}};
 const loadFriendStatus=async(p:Person)=>{try{const s=await api(`/friends/status/${encodeURIComponent(p.id)}`);setFriendStates(v=>({...v,[p.id]:s}));}catch(e){setError(e instanceof Error?e.message:'Could not load friend status.');}};
 useEffect(()=>{if(user&&open)void loadPeople(query);},[open,user]);useEffect(()=>{if(!user||!open)return;const t=window.setTimeout(()=>void loadPeople(query),250);return()=>window.clearTimeout(t);},[query,open,user]);useEffect(()=>{if(!open||!conversation)return;const t=window.setInterval(()=>void loadMessages(conversation),4000);return()=>window.clearInterval(t);},[open,conversation]);useEffect(()=>{if(open&&people.length)people.slice(0,50).forEach(p=>{if(!friendStates[p.id])void loadFriendStatus(p);});},[open,people]);
 const sendFriendRequest=async(p:Person)=>{if(busy)return;setBusy(true);setError('');try{const s=await api('/friends/request',{method:'POST',body:JSON.stringify({addressee_id:p.id})});setFriendStates(v=>({...v,[p.id]:s}));}catch(e){setError(e instanceof Error?e.message:'Friend request failed.');}finally{setBusy(false);}};
 const acceptFriendRequest=async(p:Person,requestId:string)=>{if(busy)return;setBusy(true);setError('');try{await api(`/friends/${encodeURIComponent(requestId)}`,{method:'PATCH',body:JSON.stringify({status:'accepted'})});setFriendStates(v=>({...v,[p.id]:{status:'accepted',requestId}}));}catch(e){setError(e instanceof Error?e.message:'Could not accept friend request.');}finally{setBusy(false);}};
 const handleFriend=async(p:Person)=>{const s=friendStates[p.id];if(s?.status==='pending'&&s.incoming&&s.requestId)return acceptFriendRequest(p,s.requestId);return sendFriendRequest(p);};
 const startChat=async(p:Person)=>{if(busy)return;setBusy(true);setError('');try{const c=await api('/conversations',{method:'POST',body:JSON.stringify({user_ids:[p.id]})});setSelected(p);setConversation(c.id);await loadMessages(c.id);}catch(e){setError(e instanceof Error?e.message:'Could not open this chat.');}finally{setBusy(false);}};
 const send=async()=>{if(!text.trim()||!conversation||busy)return;setBusy(true);setError('');try{const m=await api(`/conversations/${conversation}/messages`,{method:'POST',body:JSON.stringify({body:text.trim()})});setMessages(v=>[...v,Array.isArray(m)?m[0]:m]);setText('');}catch(e){setError(e instanceof Error?e.message:'Message could not be sent.');}finally{setBusy(false);}};
 if(!user)return null;const initials=(p?:Person|null)=>(p?.full_name||p?.username||'OL').split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase();const label=(p:Person)=>{const s=friendStates[p.id];if(s?.status==='accepted')return'Friends';if(s?.status==='pending')return s.incoming?'Accept':'Requested';return'Add friend';};
 return <>
 {!open&&<button aria-label="Open OLANET Messages" onClick={()=>setOpen(true)} className="fixed bottom-24 right-4 z-[60] grid h-14 w-14 place-items-center rounded-full bg-[#2f817d] text-white shadow-lg hover:bg-[#276d69]"><MessageCircle size={25}/></button>}
 {open&&<div className="fixed inset-0 z-[70] bg-[#eef4f2]">
  <div className="mx-auto flex h-full max-w-6xl flex-col overflow-hidden bg-white shadow-2xl sm:my-5 sm:h-[calc(100%-40px)] sm:rounded-2xl">
   <header className="flex shrink-0 items-center justify-between border-b border-[#dbe6e3] bg-white px-4 py-3"><div className="flex items-center gap-3"><button onClick={()=>{setSelected(null);setConversation(null);setMessages([]);}} className="grid h-10 w-10 place-items-center rounded-full bg-[#eef4f2] text-[#275b5a] hover:bg-[#e3eeeb]"><ArrowLeft size={19}/></button><div><h1 className="text-lg font-extrabold text-[#173f40]">OLANET Messages</h1><p className="text-xs text-[#6a7c7d]">Friends and private conversations</p></div></div><button onClick={()=>setOpen(false)} className="grid h-10 w-10 place-items-center rounded-full bg-[#eef4f2] text-[#516465]"><X size={19}/></button></header>
   {error&&<div role="alert" className="border-b border-[#f1c8c0] bg-[#fff3f0] px-4 py-2 text-xs font-semibold text-[#9b5148]">{error}</div>}
   <div className="flex min-h-0 flex-1">
    <aside className={`${selected?'hidden sm:flex':'flex'} w-full shrink-0 flex-col border-r border-[#dbe6e3] bg-white sm:w-[350px]`}>
     <div className="border-b border-[#edf1f0] p-4"><div className="flex items-center gap-2 rounded-xl bg-[#f1f5f4] px-3 ring-1 ring-transparent focus-within:ring-[#75aaa5]"><Search size={18} className="text-[#6b7d7d]"/><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void loadPeople(query)}} placeholder="Search people on OLANET" className="min-w-0 flex-1 bg-transparent py-3 text-sm outline-none"/><button onClick={()=>void loadPeople(query)} className="rounded-lg p-1 text-[#2f817d]" aria-label="Search"><Search size={17}/></button></div></div>
     <div className="flex-1 overflow-y-auto p-2">{people.map(p=>{const s=friendStates[p.id];return <div key={p.id} className="group flex items-center gap-3 rounded-xl p-3 hover:bg-[#f3f7f6]"><div className="grid h-12 w-12 shrink-0 place-items-center overflow-hidden rounded-full bg-[#dcefeb] font-extrabold text-[#2f817d]">{p.avatar_url?<img src={p.avatar_url} alt="" className="h-full w-full object-cover"/>:initials(p)}</div><div className="min-w-0 flex-1"><p className="truncate font-bold text-[#173f40]">{p.full_name||p.username||'OLANET user'}</p><p className="truncate text-xs text-[#718182]">@{p.username||'member'}</p>{p.bio&&<p className="mt-0.5 truncate text-xs text-[#8a9999]">{p.bio}</p>}<div className="mt-2 flex gap-2"><button onClick={()=>void handleFriend(p)} disabled={busy||s?.status==='accepted'||(s?.status==='pending'&&!s?.incoming)} className="inline-flex items-center gap-1 rounded-lg bg-[#2f817d] px-3 py-1.5 text-xs font-bold text-white shadow-sm hover:bg-[#276d69] disabled:opacity-50"><UserPlus size={13}/>{label(p)}</button><button onClick={()=>void startChat(p)} disabled={busy} className="rounded-lg bg-[#e9f0ee] px-3 py-1.5 text-xs font-bold text-[#285354] hover:bg-[#dfeae7] disabled:opacity-50">Message</button></div></div></div>})}{!people.length&&<div className="px-6 py-14 text-center text-sm text-[#718182]"><Users className="mx-auto mb-3 text-[#5c9691]" size={25}/>{query?'No matching OLANET users.':'No other users found yet.'}</div>}</div>
    </aside>
    <main className={`${selected?'flex':'hidden sm:flex'} min-w-0 flex-1 flex-col bg-[#f6f9f8]`}>
     {selected?<><header className="flex shrink-0 items-center gap-3 border-b border-[#dbe6e3] bg-white px-4 py-3"><div className="grid h-11 w-11 place-items-center overflow-hidden rounded-full bg-[#dcefeb] font-extrabold text-[#2f817d]">{selected.avatar_url?<img src={selected.avatar_url} alt="" className="h-full w-full object-cover"/>:initials(selected)}</div><div><p className="font-extrabold text-[#173f40]">{selected.full_name||selected.username||'OLANET user'}</p><p className="text-xs text-[#718182]">Private conversation</p></div></header><div className="flex-1 overflow-y-auto px-4 py-5 sm:px-8">{messages.map(m=><div key={m.id} className={`mb-2 flex ${m.sender_id===user.id?'justify-end':'justify-start'}`}><div className={`max-w-[78%] rounded-2xl px-4 py-2.5 text-sm leading-6 shadow-sm ${m.sender_id===user.id?'rounded-br-md bg-[#2f817d] text-white':'rounded-bl-md bg-white text-[#244a4b]'}`}>{m.body}</div></div>)}{!messages.length&&<div className="flex h-full items-center justify-center"><div className="rounded-2xl bg-white px-7 py-6 text-center shadow-sm"><MessageCircle className="mx-auto mb-2 text-[#5c9691]" size={30}/><p className="font-bold text-[#244a4b]">Start your private conversation</p><p className="mt-1 text-xs text-[#718182]">Messages here are between you and this person only.</p></div></div>}</div><div className="border-t border-[#dbe6e3] bg-white p-3 sm:p-4"><div className="mx-auto flex max-w-4xl items-end gap-2 rounded-2xl bg-[#f1f5f4] p-1.5"><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void send()}} placeholder="Write a message…" className="min-w-0 flex-1 bg-transparent px-3 py-2.5 text-sm outline-none"/><button onClick={()=>void send()} disabled={!text.trim()||busy} className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#2f817d] text-white hover:bg-[#276d69] disabled:opacity-40" aria-label="Send message"><Send size={17}/></button></div></div></>:<div className="m-auto max-w-md px-6 text-center"><div className="mx-auto mb-4 grid h-16 w-16 place-items-center rounded-full bg-[#dcefeb] text-[#2f817d]"><MessageCircle size={30}/></div><h2 className="text-xl font-extrabold text-[#173f40]">Your messages</h2><p className="mt-2 text-sm leading-6 text-[#718182]">Search for an OLANET member on the left, add them as a friend, or open a private conversation.</p></div>}
    </main>
   </div>
  </div>
 </div>}
 </>;
}
