import { useEffect, useRef, useState } from 'react';
import { Bookmark, ChevronRight, ImagePlus, MessageCircle, MoreHorizontal, Search, Settings, Share2, ThumbsUp, UserRound, Users, X } from 'lucide-react';
import { AuthScreen } from '@/components/auth-screen';
import { useAuth } from '@/lib/auth';

type Author={id:string;full_name?:string|null;username?:string|null;avatar_url?:string|null;bio?:string|null};
type Comment={id?:number;user_id?:string;body?:string|null;created_at?:string|null};
type FeedPost={id:number;user_id:string;content?:string|null;created_at?:string|null;circle_id?:number|null;image_url?:string|null;media_url?:string|null;author:Author;likes:number;liked:boolean;comments:number;shares:number};
const bg='#f0f2f5';
const api=async(path:string,init?:RequestInit)=>{const r=await fetch(`/api${path}`,{...init,credentials:'include',headers:{'Content-Type':'application/json',...(init?.headers||{})}});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.error||'Request failed');return d};
const initials=(p:Author)=>((p.full_name||p.username||'OLANET').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'OL');
function Avatar({p,size=44}:{p:Author,size?:number}){return <div style={{width:size,height:size}} className="relative shrink-0 overflow-hidden rounded-full bg-[#e4e6eb] text-[#1877f2] font-extrabold flex items-center justify-center">{initials(p)}{p.avatar_url&&<img src={p.avatar_url} alt="" className="absolute inset-0 h-full w-full object-cover"/>}</div>}
function timeAgo(value?:string|null){if(!value)return 'Just now';const d=Date.now()-new Date(value).getTime();const m=Math.max(0,Math.floor(d/60000));if(m<1)return 'Just now';if(m<60)return `${m}m`;const h=Math.floor(m/60);if(h<24)return `${h}h`;return `${Math.floor(h/24)}d`;}
export default function HomeHub(){
 const {user,logout,status}=useAuth();
 const fileRef=useRef<HTMLInputElement>(null);
 const [posts,setPosts]=useState<FeedPost[]>([]),[loading,setLoading]=useState(true),[text,setText]=useState(''),[image,setImage]=useState(''),[posting,setPosting]=useState(false),[openComments,setOpenComments]=useState<number|null>(null),[comments,setComments]=useState<Record<number,Comment[]>>({}),[busy,setBusy]=useState<Record<string,boolean>>({}),[notice,setNotice]=useState('');
 const profile:Author={id:user?.id||'',full_name:user?.profile?.full_name||user?.email||'OLANET member',username:user?.profile?.username||null,avatar_url:user?.profile?.avatar_url||null,bio:user?.profile?.bio||null};
 async function load(){setLoading(true);try{const d=await api('/feed');setPosts(Array.isArray(d?.posts)?d.posts:[]);setNotice('')}catch(e){setNotice(e instanceof Error?e.message:'Could not load feed')}finally{setLoading(false)}}
 useEffect(()=>{if(status==='authenticated')void load();else if(status==='unauthenticated')setLoading(false)},[status]);
 if(status==='loading')return <div className="min-h-[100dvh] bg-[#f0f2f5] flex items-center justify-center text-sm text-[#65676b]">Loading OLANET...</div>;
 if(status==='unauthenticated')return <AuthScreen/>;
 function chooseImage(){fileRef.current?.click()}
 function handleImage(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)){setNotice('Please choose a JPG, PNG or WebP image.');e.target.value='';return}if(file.size>1600000){setNotice('Image is too large. Choose an image under 1.6 MB.');e.target.value='';return}const reader=new FileReader();reader.onload=()=>setImage(typeof reader.result==='string'?reader.result:'');reader.readAsDataURL(file)}
 async function publish(){if((!text.trim()&&!image)||posting)return;setPosting(true);setNotice('');try{await api('/feed',{method:'POST',body:JSON.stringify({content:text.trim(),image_url:image||null})});setText('');setImage('');if(fileRef.current)fileRef.current.value='';await load()}catch(e){setNotice(e instanceof Error?e.message:'Could not publish post')}finally{setPosting(false)}}
 async function like(post:FeedPost){const key=`like-${post.id}`;setBusy(v=>({...v,[key]:true}));try{const d=await api(`/posts/${post.id}/like`,{method:'POST'});setPosts(v=>v.map(p=>p.id===post.id?{...p,liked:Boolean(d?.liked),likes:Math.max(0,p.likes+(d?.liked?1:-1))}:p))}catch(e){setNotice(e instanceof Error?e.message:'Could not update like')}finally{setBusy(v=>({...v,[key]:false}))}}
 async function toggleComments(post:FeedPost){setOpenComments(v=>v===post.id?null:post.id);if(openComments===post.id||comments[post.id])return;try{const d=await api(`/posts/${post.id}/interactions`);setComments(v=>({...v,[post.id]:Array.isArray(d?.comments)?d.comments:[]}));setPosts(v=>v.map(p=>p.id===post.id?{...p,likes:Number(d?.likes??p.likes),liked:Boolean(d?.liked),comments:Array.isArray(d?.comments)?d.comments.length:p.comments,shares:Number(d?.shares??p.shares)}:p))}catch(e){setNotice(e instanceof Error?e.message:'Could not load comments')}}
 async function comment(post:FeedPost,body:string){const key=`comment-${post.id}`;setBusy(v=>({...v,[key]:true}));try{const d=await api(`/posts/${post.id}/comments`,{method:'POST',body:JSON.stringify({body})});const created=Array.isArray(d)?d[0]:d;setComments(v=>({...v,[post.id]:[...(v[post.id]||[]),created]}));setPosts(v=>v.map(p=>p.id===post.id?{...p,comments:p.comments+1}:p))}catch(e){setNotice(e instanceof Error?e.message:'Could not add comment')}finally{setBusy(v=>({...v,[key]:false}))}}
 async function share(post:FeedPost){const key=`share-${post.id}`;setBusy(v=>({...v,[key]:true}));try{const d=await api(`/posts/${post.id}/share`,{method:'POST'});if(d?.shared&&!d?.duplicate)setPosts(v=>v.map(p=>p.id===post.id?{...p,shares:p.shares+1}:p));setNotice(d?.duplicate?'You already shared this post.':'Post shared.')}catch(e){setNotice(e instanceof Error?e.message:'Could not share post')}finally{setBusy(v=>({...v,[key]:false}))}}
 return <div className="min-h-[100dvh]" style={{background:bg,color:'#1c1e21'}}>
  <header className="sticky top-0 z-30 border-b border-[#dddfe2] bg-white"><div className="mx-auto flex h-16 max-w-7xl items-center gap-3 px-3 sm:px-5"><a href="/" className="text-2xl font-extrabold text-[#1877f2]">OLANET</a><div className="hidden max-w-xs flex-1 sm:flex"><div className="flex w-full items-center gap-2 rounded-full bg-[#f0f2f5] px-3 py-2"><Search size={18} className="text-[#65676b]"/><input placeholder="Search OLANET" onFocus={()=>{window.location.href='/people'}} className="w-full bg-transparent text-sm outline-none"/></div></div><nav className="ml-auto flex items-center gap-1"><a href="/people" className="rounded-full p-3 hover:bg-[#f0f2f5]" title="People"><Users size={20}/></a><a href="/messages" className="rounded-full p-3 hover:bg-[#f0f2f5]" title="Messages"><MessageCircle size={20}/></a><a href="/profile" className="rounded-full p-3 hover:bg-[#f0f2f5]" title="Profile"><UserRound size={20}/></a><a href="/settings" className="rounded-full p-3 hover:bg-[#f0f2f5]" title="Settings"><Settings size={20}/></a></nav></div></header>
  <main className="mx-auto grid max-w-7xl gap-5 px-3 py-4 sm:px-5 lg:grid-cols-[250px_minmax(0,680px)_250px]">
   <aside className="hidden self-start lg:block"><div className="rounded-xl bg-white p-2 shadow-sm"><a href="/profile" className="flex items-center gap-3 rounded-lg px-3 py-3 font-bold hover:bg-[#f0f2f5]"><Avatar p={profile} size={34}/><span className="truncate">{profile.full_name}</span></a><a href="/people" className="flex items-center gap-3 rounded-lg px-3 py-3 font-semibold hover:bg-[#f0f2f5]"><Users size={20} className="text-[#1877f2]"/>Find people</a><a href="/circles" className="flex items-center gap-3 rounded-lg px-3 py-3 font-semibold hover:bg-[#f0f2f5]"><Bookmark size={20} className="text-[#1877f2]"/>Departments</a><a href="/messages" className="flex items-center gap-3 rounded-lg px-3 py-3 font-semibold hover:bg-[#f0f2f5]"><MessageCircle size={20} className="text-[#1877f2]"/>Messages</a><a href="/settings" className="flex items-center gap-3 rounded-lg px-3 py-3 font-semibold hover:bg-[#f0f2f5]"><Settings size={20} className="text-[#1877f2]"/>Settings</a><button onClick={()=>void logout()} className="mt-1 w-full rounded-lg px-3 py-3 text-left font-semibold hover:bg-[#f0f2f5]">Log out</button></div></aside>
   <section className="min-w-0 space-y-3">
    {notice&&<div className="rounded-lg border border-[#f3b5ae] bg-[#fff2ef] px-4 py-3 text-sm font-semibold text-[#b42318]">{notice}</div>}
    <div className="rounded-xl bg-white p-4 shadow-sm"><div className="flex items-center gap-3"><Avatar p={profile}/><button onClick={()=>document.getElementById('post-box')?.focus()} className="flex-1 rounded-full bg-[#f0f2f5] px-4 py-3 text-left text-sm text-[#65676b]">What's on your mind?</button></div><textarea id="post-box" value={text} onChange={e=>setText(e.target.value)} placeholder="Write something useful to the OLANET community..." className={`mt-3 ${text||image?'block':'hidden'} min-h-24 w-full rounded-xl border border-[#dddfe2] px-3 py-3 text-sm outline-none focus:border-[#1877f2]`}/>{image&&<div className="relative mt-3 overflow-hidden rounded-xl border border-[#dddfe2]"><img src={image} alt="Selected post" className="max-h-72 w-full object-contain"/><button onClick={()=>{setImage('');if(fileRef.current)fileRef.current.value=''}} className="absolute right-2 top-2 rounded-full bg-black/70 p-2 text-white"><X size={18}/></button></div>}{(text||image)&&<div className="mt-3 flex justify-end gap-2"><button onClick={()=>{setText('');setImage('');if(fileRef.current)fileRef.current.value=''}} className="rounded-lg bg-[#e4e6eb] px-4 py-2 text-sm font-bold">Cancel</button><button onClick={()=>void publish()} disabled={posting} className="rounded-lg bg-[#1877f2] px-5 py-2 text-sm font-bold text-white disabled:opacity-50">{posting?'Posting…':'Post'}</button></div>}<input ref={fileRef} type="file" accept="image/jpeg,image/png,image/webp" onChange={handleImage} className="hidden"/><div className="mt-3 border-t border-[#e4e6eb] pt-3 flex justify-around text-sm font-bold text-[#65676b]"><button onClick={chooseImage} className="flex items-center gap-2 rounded-lg px-4 py-2 hover:bg-[#f0f2f5]"><ImagePlus size={20} className="text-[#45bd62]"/>Photo / post</button><a href="/circles" className="flex items-center gap-2 rounded-lg px-4 py-2 hover:bg-[#f0f2f5]"><Users size={20} className="text-[#1877f2]"/>Department</a></div></div>
    {loading&&<div className="rounded-xl bg-white p-8 text-center text-sm text-[#65676b]">Loading your feed...</div>}
    {!loading&&!posts.length&&<div className="rounded-xl bg-white p-10 text-center text-[#65676b]"><p className="font-bold text-[#1c1e21]">Your feed is empty.</p><p className="mt-1 text-sm">Create the first useful post on OLANET.</p></div>}
    {posts.map(post=><article key={post.id} className="rounded-xl bg-white shadow-sm"><div className="p-4"><div className="flex items-center gap-3"><Avatar p={post.author}/><div className="min-w-0 flex-1"><p className="truncate font-extrabold">{post.author.full_name||post.author.username||'OLANET member'}</p><p className="text-xs text-[#65676b]">@{post.author.username||'member'} · {timeAgo(post.created_at)}</p></div><button className="rounded-full p-2 hover:bg-[#f0f2f5]"><MoreHorizontal size={20}/></button></div>{post.content&&<p className="mt-3 whitespace-pre-wrap text-[15px] leading-6">{post.content}</p>}{(post.image_url||post.media_url)&&<img src={post.image_url||post.media_url||''} alt="Post media" className="mt-3 max-h-[520px] w-full rounded-lg object-cover"/>}<div className="mt-3 flex items-center justify-between border-b border-[#e4e6eb] pb-3 text-xs text-[#65676b]"><span>{post.likes} likes</span><span>{post.comments} comments · {post.shares} shares</span></div><div className="grid grid-cols-3 pt-1"><button disabled={busy[`like-${post.id}`]} onClick={()=>void like(post)} className={`flex items-center justify-center gap-2 rounded-lg py-2.5 text-sm font-bold hover:bg-[#f0f2f5] ${post.liked?'text-[#1877f2]':'text-[#65676b]'}`}><ThumbsUp size={18} fill={post.liked?'currentColor':'none'}/>Like</button><button onClick={()=>void toggleComments(post)} className="flex items-center justify-center gap-2 rounded-lg py-2.5 text-sm font-bold text-[#65676b] hover:bg-[#f0f2f5]"><MessageCircle size={18}/>Comment</button><button disabled={busy[`share-${post.id}`]} onClick={()=>void share(post)} className="flex items-center justify-center gap-2 rounded-lg py-2.5 text-sm font-bold text-[#65676b] hover:bg-[#f0f2f5]"><Share2 size={18}/>Share</button></div>{openComments===post.id&&<div className="mt-2 border-t border-[#e4e6eb] pt-3">{(comments[post.id]||[]).map((c,i)=><div key={c.id??i} className="mb-2 rounded-2xl bg-[#f0f2f5] px-3 py-2 text-sm"><p className="whitespace-pre-wrap">{c.body}</p></div>)}{!(comments[post.id]||[]).length&&<p className="mb-2 text-sm text-[#65676b]">No comments yet.</p>}<CommentBox onSubmit={(body)=>void comment(post,body)} busy={Boolean(busy[`comment-${post.id}`])}/></div>}</div></article>)}
   </section>
   <aside className="hidden self-start xl:block"><div className="rounded-xl bg-white p-4 shadow-sm"><p className="text-xs font-bold uppercase tracking-wide text-[#65676b]">OLANET</p><p className="mt-1 font-extrabold">Build, learn, connect.</p><p className="mt-2 text-sm text-[#65676b]">Find classmates, join your department, share practical knowledge and keep conversations in one place.</p><a href="/circles" className="mt-3 inline-flex items-center gap-1 text-sm font-bold text-[#1877f2]">Explore departments <ChevronRight size={16}/></a></div></aside>
  </main>
 </div>;
}
function CommentBox({onSubmit,busy}:{onSubmit:(body:string)=>void;busy:boolean}){const [value,setValue]=useState('');return <div className="flex items-center gap-2"><Avatar p={{id:'me',full_name:'You'}} size={34}/><div className="flex flex-1 items-center gap-2 rounded-full bg-[#f0f2f5] px-3"><input value={value} onChange={e=>setValue(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&value.trim()){onSubmit(value.trim());setValue('')}}} placeholder="Write a comment..." className="min-w-0 flex-1 bg-transparent py-2.5 text-sm outline-none"/><button disabled={!value.trim()||busy} onClick={()=>{if(value.trim()){onSubmit(value.trim());setValue('')}}} className="text-[#1877f2] disabled:opacity-30"><MessageCircle size={18}/></button></div></div>}
