import { FormEvent, useState } from 'react';
import { ArrowLeft, Bell, Lock, LogOut, Settings, ShieldCheck } from 'lucide-react';

export default function SettingsHub(){
  const [email,setEmail]=useState('');
  const [password,setPassword]=useState('');
  const [busy,setBusy]=useState(false);
  const [message,setMessage]=useState('');
  const [error,setError]=useState('');
  async function save(e:FormEvent){e.preventDefault();setBusy(true);setMessage('');setError('');try{const r=await fetch('/api/settings/account',{method:'PATCH',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({...(email.trim()?{email:email.trim()}:{}),...(password?{password}: {})})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.error||'Unable to update account');setMessage('Account settings updated.');setPassword('');}catch(err){setError(err instanceof Error?err.message:'Unable to update account');}finally{setBusy(false)}}
  async function signOut(){try{await fetch('/api/auth/logout',{method:'POST',credentials:'include'});}catch{}window.location.href='/';}
  return <div className="min-h-[100dvh] bg-[#eef2f4] text-[#1c2b33]"><header className="sticky top-0 z-10 border-b border-[#d9e1e4] bg-white"><div className="mx-auto flex max-w-4xl items-center gap-3 px-4 py-3"><a href="/" className="rounded-full p-2 hover:bg-[#f0f2f5]"><ArrowLeft size={20}/></a><Settings size={21}/><h1 className="text-xl font-extrabold">Settings</h1></div></header><main className="mx-auto max-w-4xl space-y-4 px-4 py-5"><div className="rounded-2xl bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><div className="rounded-full bg-[#e8f3f2] p-3 text-[#2f817d]"><ShieldCheck size={21}/></div><div><h2 className="font-extrabold">Account & security</h2><p className="text-sm text-[#718088]">Update your login details. Password changes require at least 8 characters.</p></div></div><form onSubmit={save} className="mt-5 space-y-3"><input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="New email address" className="w-full rounded-xl border border-[#dfe5e8] bg-white px-4 py-3 text-sm outline-none focus:border-[#2f817d]"/><input value={password} onChange={e=>setPassword(e.target.value)} type="password" minLength={8} placeholder="New password" className="w-full rounded-xl border border-[#dfe5e8] bg-white px-4 py-3 text-sm outline-none focus:border-[#2f817d]"/><button disabled={busy||(!email.trim()&&!password)} className="rounded-xl bg-[#2f817d] px-4 py-3 text-sm font-extrabold text-white disabled:opacity-50">{busy?'Saving…':'Save changes'}</button></form>{message&&<p className="mt-3 rounded-xl bg-[#e8f3f2] px-3 py-2 text-sm font-bold text-[#216763]">{message}</p>}{error&&<p className="mt-3 rounded-xl bg-[#fff0ed] px-3 py-2 text-sm font-bold text-[#9b4337]">{error}</p>}</div><div className="rounded-2xl bg-white p-5 shadow-sm"><Row icon={Bell} title="Notifications" text="Notification preferences are managed from the app alerts."/><Row icon={Lock} title="Privacy" text="Keep your profile and connections under your control."/><button type="button" onClick={signOut} className="flex w-full items-center gap-3 border-b border-[#eef1f2] py-4 text-left hover:bg-[#fafbfb]"><div className="rounded-full bg-[#f0f2f5] p-2"><LogOut size={18}/></div><div><p className="font-bold">Sign out</p><p className="text-sm text-[#718088]">End your current OLANET session.</p></div></button></div></main></div>}
function Row({icon:Icon,title,text}:{icon:typeof Bell;title:string;text:string}){return <div className="flex items-center gap-3 border-b border-[#eef1f2] py-4 last:border-0"><div className="rounded-full bg-[#f0f2f5] p-2"><Icon size={18}/></div><div><p className="font-bold">{title}</p><p className="text-sm text-[#718088]">{text}</p></div></div>}
