import { useEffect, useMemo, useRef, useState } from 'react';
import { MessageCircle, Users, Send, Plus, Share2, X, Search, LogOut, Settings, Camera, Eye, EyeOff, ChevronRight, UserRound, Lock, Bell, Check } from 'lucide-react';
import { useAuth } from '@/lib/auth';

type Group={id:number;name:string;description?:string|null;created_by:string};
type Person={id:string;full_name?:string|null;username?:string|null;avatar_url?:string|null;bio?:string|null;department?:string|null};
type Chat={id:number;conversation_id?:number|null;group_id?:number|null;sender_id:string;body:string;created_at:string;is_view_once?:boolean};
const api=(path:string,init?:RequestInit)=>fetch(`/api${path}`,{...init,credentials:'include',headers:{'Content-Type':'application/json',...(init?.headers||{})}}).then(async r=>{const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.error||'Request failed');return d;});

export function SocialHub(){
 const {user,logout,updateProfile,uploadAvatar}=useAuth();
 const [open,setOpen]=useState(false),[tab,setTab]=useState<'chat'|'groups'|'people'>('chat'),[groups,setGroups]=useState<Group[]>([]),[selectedGroup,setSelectedGroup]=useState<Group|null>(null),[conversation,setConversation]=useState<number|null>(null),[messages,setMessages]=useState<Chat[]>([]),[text,setText]=useState(''),[newGroup,setNewGroup]=useState(''),[search,setSearch]=useState(''),[people,setPeople]=useState<Person[]>([]),[busy,setBusy]=useState(false),[viewOnce,setViewOnce]=useState(false),[settingsOpen,setSettingsOpen]=useState(false),[name,setName]=useState(user?.profile?.full_name||''),[bio,setBio]=useState(user?.profile?.bio||''),[password,setPassword]=useState(''),[notice,setNotice]=useState('');
 const fileRef=useRef<HTMLInputElement>(null); const initials=useMemo(()=>{const n=user?.profile?.full_name||user?.email?.split('@')[0]||'OL';return n.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()},[user]);
 const loadGroups=async(q='')=>setGroups(await api(`/groups${q?`?q=${encodeURIComponent(q)}`:''}`)); const loadPeople=async(q='')=>setPeople(await api(`/people${q?`?q=${encodeURIComponent(q)}`:''}`));
 const loadMessages=async()=>{const p=selectedGroup?`/groups/${selectedGroup.id}/messages`:conversation?`/conversations/${conversation}/messages`:'';if(p)setMessages(await api(p));};
 useEffect(()=>{if(open)loadGroups().catch(()=>undefined)},[open]); useEffect(()=>{if(open&&tab==='people')loadPeople(search).catch(()=>undefined)},[open,tab]); useEffect(()=>{if(!open)return;const t=window.setInterval(()=>loadMessages().catch(()=>undefined),5000);return()=>window.clearInterval(t)},[selectedGroup,conversation,open]);
 async function createGroup(){if(!newGroup.trim()||busy)return;setBusy(true);try{const g=await api('/groups',{method:'POST',body:JSON.stringify({name:newGroup.trim()})});setGroups(v=>[g,...v]);setNewGroup('');setSelectedGroup(g);setConversation(null)}finally{setBusy(false)}}
 async function joinGroup(g:Group){setBusy(true);try{await api(`/groups/${g.id}/join`,{method:'POST'});setSelectedGroup(g);setConversation(null);setMessages(await api(`/groups/${g.id}/messages`))}finally{setBusy(false)}}
 async function startChat(p:Person){setBusy(true);try{const c=await api('/conversations',{method:'POST',body:JSON.stringify({user_ids:[p.id]})});setConversation(c.id);setSelectedGroup(null);setMessages(await api(`/conversations/${c.id}/messages`));setTab('chat')}finally{setBusy(false)}}
 async function send(){if(!text.trim()||busy||(!selectedGroup&&!conversation))return;setBusy(true);try{const p=selectedGroup?`/groups/${selectedGroup.id}/messages`:`/conversations/${conversation}/messages`;const m=await api(p,{method:'POST',body:JSON.stringify({body:text,is_view_once:viewOnce})});setMessages(v=>[...v,(Array.isArray(m)?m[0]:m)]);setText('');setViewOnce(false)}finally{setBusy(false)}}
 async function openViewOnce(m:Chat){try{await api(`/messages/${m.id}/view-once`,{method:'POST'});setMessages(v=>v.map(x=>x.id===m.id?{...x,body:'This view-once message has been opened.',is_view_once:false}:x))}catch{setNotice('This message is no longer available.')}}
 async function saveSettings(){setBusy(true);setNotice('');try{await updateProfile({full_name:name.trim()||null,bio:bio.trim()||null});if(password.trim()){await api('/settings/account',{method:'PATCH',body:JSON.stringify({password})});setPassword('')}setNotice('Changes saved')}catch(e){setNotice(e instanceof Error?e.message:'Could not save changes')}finally{setBusy(false)}}
 async function avatar(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;try{await uploadAvatar(f);setNotice('Profile picture updated')}catch(e){setNotice(e instanceof Error?e.message:'Upload failed')}}
 return <>
 <button aria-label="Open OLANET Social" onClick={()=>setOpen(true)} className="fixed bottom-5 right-5 z-30 flex h-14 w-14 items-center justify-center rounded-full bg-[#1d4348] text-[#fffaf1] shadow-xl hover:scale-105 transition"><MessageCircle size={24}/></button>
 {open&&<div className="fixed inset-0 z-50 bg-[#17383b]/35 p-2 sm:p-6"><div className="mx-auto flex h-full max-w-5xl flex-col overflow-hidden rounded-3xl border border-[#dfd2c0] bg-[#fffaf1] shadow-2xl">
 <header className="flex items-center justify-between border-b border-[#eadfce] p-4"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-[#e8c17a] font-extrabold text-[#1d4348]">{initials}</div><div><p className="text-xs font-bold uppercase tracking-widest text-[#2f817d]">OLANET</p><h2 className="text-xl font-extrabold text-[#1d4348]">Connect, learn, build.</h2></div></div><div className="flex items-center"><button title="Settings" onClick={()=>setSettingsOpen(true)} className="rounded-full p-2 hover:bg-[#f1e4cc]"><Settings size={20}/></button><button onClick={()=>setOpen(false)} className="rounded-full p-2 hover:bg-[#f1e4cc]"><X/></button></div></header>
 <div className="flex flex-1 min-h-0"><aside className="w-64 shrink-0 border-r border-[#eadfce] p-3 hidden sm:block"><div className="mb-3 grid grid-cols-3 gap-1"><button onClick={()=>setTab('chat')} className={`rounded-xl p-2 text-xs font-bold ${tab==='chat'?'bg-[#dceceb] text-[#216763]':''}`}><MessageCircle className="mx-auto mb-1" size={18}/>Chat</button><button onClick={()=>setTab('groups')} className={`rounded-xl p-2 text-xs font-bold ${tab==='groups'?'bg-[#dceceb] text-[#216763]':''}`}><Users className="mx-auto mb-1" size={18}/>Groups</button><button onClick={()=>setTab('people')} className={`rounded-xl p-2 text-xs font-bold ${tab==='people'?'bg-[#dceceb] text-[#216763]':''}`}><UserRound className="mx-auto mb-1" size={18}/>People</button></div><button onClick={()=>setSettingsOpen(true)} className="w-full rounded-xl border border-[#dfd2c0] p-3 text-left text-sm font-bold flex items-center gap-2"><Settings size={16}/> Settings <ChevronRight className="ml-auto" size={15}/></button></aside>
 <main className="flex min-w-0 flex-1 flex-col"><div className="flex gap-1 border-b border-[#eadfce] p-2 sm:hidden"><button onClick={()=>setTab('chat')} className="flex-1 rounded-xl p-2 text-xs font-bold">Chat</button><button onClick={()=>setTab('groups')} className="flex-1 rounded-xl p-2 text-xs font-bold">Groups</button><button onClick={()=>setTab('people')} className="flex-1 rounded-xl p-2 text-xs font-bold">People</button></div>
 {!selectedGroup&&!conversation?<div className="flex h-full flex-col p-5">
 {tab==='people'&&<><div className="mb-4 flex items-center gap-2 rounded-xl border border-[#dfd2c0] bg-[#f8f2e8] px-3"><Search size={17}/><input value={search} onChange={e=>{setSearch(e.target.value);loadPeople(e.target.value).catch(()=>undefined)}} placeholder="Search OLANET members" className="w-full bg-transparent p-3 outline-none"/></div><div className="space-y-2 overflow-auto">{people.map(p=><button key={p.id} onClick={()=>startChat(p)} className="w-full rounded-2xl border border-[#dfd2c0] p-3 text-left hover:border-[#2f817d] flex items-center gap-3"><div className="h-10 w-10 overflow-hidden rounded-full bg-[#e8c17a] flex items-center justify-center font-bold">{p.avatar_url?<img src={p.avatar_url} alt="" className="h-full w-full object-cover"/>:(p.full_name||p.username||'?').slice(0,2).toUpperCase()}</div><div><b>{p.full_name||p.username||'OLANET member'}</b><p className="text-xs text-[#789093]">{p.department||p.bio||'Member'}</p></div></button>)}</div></>}
 {tab==='groups'&&<><div className="mb-3 flex gap-2"><div className="flex flex-1 items-center gap-2 rounded-xl border border-[#dfd2c0] bg-[#f8f2e8] px-3"><Search size={17}/><input value={search} onChange={e=>{setSearch(e.target.value);loadGroups(e.target.value).catch(()=>undefined)}} placeholder="Find a group" className="w-full bg-transparent p-3 outline-none"/></div></div><div className="flex gap-2 mb-4"><input value={newGroup} onChange={e=>setNewGroup(e.target.value)} placeholder="New group name" className="min-w-0 flex-1 rounded-xl border border-[#dfd2c0] bg-white p-3 outline-none"/><button onClick={createGroup} disabled={!newGroup.trim()||busy} className="rounded-xl bg-[#2f817d] px-3 text-white"><Plus/></button></div><div className="grid gap-3 sm:grid-cols-2 overflow-auto">{groups.map(g=><div key={g.id} className="rounded-2xl border border-[#dfd2c0] p-4"><div className="flex items-center gap-3"><div className="rounded-xl bg-[#e8c17a] p-2"><Users size={18}/></div><div className="min-w-0"><b>{g.name}</b><p className="text-xs text-[#789093]">{g.description||'Community group'}</p></div></div><button onClick={()=>joinGroup(g)} className="mt-3 w-full rounded-xl bg-[#1d4348] py-2 text-xs font-bold text-white">Open / join group</button></div>)}</div></>}
 {tab==='chat'&&<div className="rounded-2xl border border-dashed border-[#d8c9b3] p-8 text-center"><MessageCircle className="mx-auto mb-3 text-[#2f817d]"/><h3 className="font-extrabold text-[#1d4348]">Your messages</h3><p className="mt-1 text-sm text-[#70878a]">Search People to start a private chat, or open Groups for community conversations.</p><button onClick={()=>setTab('people')} className="mt-4 rounded-xl bg-[#2f817d] px-4 py-2 text-sm font-bold text-white">Find people</button></div>}
 </div>:<><div className="flex items-center gap-3 border-b border-[#eadfce] p-4"><button onClick={()=>{setSelectedGroup(null);setConversation(null);setMessages([])}} className="rounded-xl p-2 hover:bg-[#f1e4cc]">←</button><div><b>{selectedGroup?.name||'Private chat'}</b><p className="text-xs text-[#789093]">{selectedGroup?'Group conversation':'Direct conversation'}</p></div></div><div className="flex-1 space-y-3 overflow-y-auto p-4">{messages.map(m=><div key={m.id} className={`max-w-[85%] rounded-2xl p-3 text-sm ${m.sender_id===user?.id?'ml-auto bg-[#dceceb] text-[#214d50]':'bg-[#f1e4cc] text-[#365b60]'}`}><div className="mb-1 text-[10px] font-bold uppercase text-[#789093]">{m.sender_id===user?.id?'You':'Member'} · {new Date(m.created_at).toLocaleString()}</div>{m.is_view_once?<button onClick={()=>openViewOnce(m)} className="flex items-center gap-2 rounded-xl bg-[#fffaf1] px-3 py-2 font-bold"><Eye size={16}/> View once</button>:m.body}</div>)}{!messages.length&&<p className="text-center text-sm text-[#789093]">No messages yet.</p>}</div><div className="border-t border-[#eadfce] p-3"><div className="mb-2 flex items-center gap-2"><button onClick={()=>setViewOnce(v=>!v)} className={`rounded-full px-3 py-1.5 text-xs font-bold border ${viewOnce?'border-[#2f817d] bg-[#dceceb] text-[#216763]':'border-[#dfd2c0]'}`}><Eye size={14} className="mr-1 inline"/>{viewOnce?'View once ON':'View once'}</button><span className="text-[10px] text-[#789093]">Opened view-once messages are consumed.</span></div><div className="flex gap-2"><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')send()}} placeholder="Write a message…" className="min-w-0 flex-1 rounded-xl border border-[#dfd2c0] bg-[#f8f2e8] p-3 outline-none"/><button onClick={send} disabled={!text.trim()||busy} className="rounded-xl bg-[#2f817d] p-3 text-white disabled:opacity-50"><Send size={18}/></button></div></div></>}
 </main></div></div></div>}
 {settingsOpen&&<div className="fixed inset-0 z-[60] bg-[#17383b]/40"><div className="ml-auto flex h-full w-full max-w-md flex-col bg-[#fffaf1] shadow-2xl"><header className="flex items-center gap-3 border-b border-[#eadfce] p-4"><button onClick={()=>setSettingsOpen(false)} className="rounded-full p-2 hover:bg-[#f1e4cc]">←</button><div><p className="text-xs font-bold uppercase tracking-widest text-[#2f817d]">OLANET</p><h2 className="text-xl font-extrabold">Settings</h2></div></header><div className="flex-1 overflow-y-auto p-5"><div className="flex items-center gap-4"><button onClick={()=>fileRef.current?.click()} className="relative"><div className="h-20 w-20 overflow-hidden rounded-full bg-[#e8c17a] flex items-center justify-center text-xl font-bold">{user?.profile?.avatar_url?<img src={user.profile.avatar_url} alt="" className="h-full w-full object-cover"/>:initials}</div><span className="absolute bottom-0 right-0 rounded-full bg-[#1d4348] p-2 text-white"><Camera size={14}/></span></button><input ref={fileRef} type="file" accept="image/*" className="hidden" onChange={avatar}/><div><b className="text-lg">{user?.profile?.full_name||'OLANET member'}</b><p className="text-xs text-[#789093]">{user?.email}</p></div></div><div className="mt-6 space-y-4"><label className="block text-xs font-bold text-[#527075]">Name<input value={name} onChange={e=>setName(e.target.value)} className="mt-2 w-full rounded-xl border border-[#dfd2c0] bg-[#f8f2e8] p-3 outline-none"/></label><label className="block text-xs font-bold text-[#527075]">Bio<textarea value={bio} onChange={e=>setBio(e.target.value)} className="mt-2 h-24 w-full rounded-xl border border-[#dfd2c0] bg-[#f8f2e8] p-3 outline-none"/></label><label className="block text-xs font-bold text-[#527075]">New password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 8 characters" className="mt-2 w-full rounded-xl border border-[#dfd2c0] bg-[#f8f2e8] p-3 outline-none"/></label><button onClick={saveSettings} disabled={busy} className="w-full rounded-xl bg-[#2f817d] p-3 font-bold text-white">{busy?'Saving…':'Save changes'}</button>{notice&&<p className="rounded-xl bg-[#dceceb] p-3 text-xs font-bold text-[#216763]">{notice}</p>}<div className="border-t border-[#eadfce] pt-5"><div className="mb-3 flex items-center gap-3 text-sm font-bold"><Lock size={17}/> Security & account</div><div className="space-y-2 text-sm text-[#527075]"><div className="flex items-center gap-3 rounded-xl bg-[#f6eddf] p-3"><Bell size={16}/> Notifications <Check className="ml-auto" size={16}/></div><div className="flex items-center gap-3 rounded-xl bg-[#f6eddf] p-3"><EyeOff size={16}/> Privacy controls</div></div></div></div></div><div className="border-t border-[#eadfce] p-5"><button onClick={()=>void logout()} className="flex w-full items-center gap-3 rounded-xl bg-[#fff0eb] p-3 font-bold text-[#b45243]"><LogOut size={18}/> Log out</button></div></div></div>}
 </>;
}
