import { useEffect, useMemo, useState } from 'react';
import { MessageCircle, Users, Send, Plus, Heart, MessageSquare, Share2, X, Search, LogOut } from 'lucide-react';

type Group={id:number;name:string;description?:string|null;created_by:string};
type Chat={id:number;conversation_id?:number|null;group_id?:number|null;sender_id:string;body:string;created_at:string};
const api=(path:string,init?:RequestInit)=>fetch(`/api${path}`,{...init,credentials:'include',headers:{'Content-Type':'application/json',...(init?.headers||{})}}).then(async r=>{const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.error||'Request failed');return d;});

export function SocialHub(){
 const [open,setOpen]=useState(false); const [tab,setTab]=useState<'chat'|'groups'>('chat'); const [groups,setGroups]=useState<Group[]>([]); const [selectedGroup,setSelectedGroup]=useState<Group|null>(null); const [messages,setMessages]=useState<Chat[]>([]); const [text,setText]=useState(''); const [newGroup,setNewGroup]=useState(''); const [search,setSearch]=useState(''); const [busy,setBusy]=useState(false);
 const initials=useMemo(()=> 'OL',[ ]);
 async function loadGroups(q=''){setGroups(await api(`/groups${q?`?q=${encodeURIComponent(q)}`:''}`));}
 async function loadGroupMessages(g:Group){setSelectedGroup(g);setMessages(await api(`/groups/${g.id}/messages`));}
 useEffect(()=>{if(open)loadGroups().catch(()=>undefined)},[open]);
 useEffect(()=>{if(!selectedGroup||!open)return;const timer=window.setInterval(()=>loadGroupMessages(selectedGroup).catch(()=>undefined),5000);return()=>window.clearInterval(timer)},[selectedGroup,open]);
 async function send(){if(!text.trim()||busy)return;setBusy(true);try{if(selectedGroup){const m=await api(`/groups/${selectedGroup.id}/messages`,{method:'POST',body:JSON.stringify({body:text})});setMessages(v=>[...v,(Array.isArray(m)?m[0]:m)]);setText('')}}finally{setBusy(false)}}
 async function createGroup(){if(!newGroup.trim()||busy)return;setBusy(true);try{const g=await api('/groups',{method:'POST',body:JSON.stringify({name:newGroup.trim()})});setGroups(v=>[g,...v]);setNewGroup('');setSelectedGroup(g)}finally{setBusy(false)}}
 return <>
  <button aria-label="Open social hub" onClick={()=>setOpen(true)} className="fixed bottom-5 right-5 z-30 flex h-14 w-14 items-center justify-center rounded-full bg-[#1d4348] text-[#fffaf1] shadow-xl hover:scale-105 transition"><MessageCircle size={24}/></button>
  {open&&<div className="fixed inset-0 z-50 bg-[#17383b]/35 p-3 sm:p-6"><div className="mx-auto flex h-full max-w-5xl flex-col overflow-hidden rounded-3xl border border-[#dfd2c0] bg-[#fffaf1] shadow-2xl">
   <header className="flex items-center justify-between border-b border-[#eadfce] p-4"><div><p className="text-xs font-bold uppercase tracking-widest text-[#2f817d]">OLANET Social</p><h2 className="text-xl font-extrabold text-[#1d4348]">Connect, learn, build.</h2></div><button onClick={()=>setOpen(false)} className="rounded-full p-2 hover:bg-[#f1e4cc]"><X/></button></header>
   <div className="flex flex-1 min-h-0"><aside className="w-64 shrink-0 border-r border-[#eadfce] p-3 hidden sm:block"><div className="mb-3 flex gap-2"><button onClick={()=>setTab('chat')} className={`flex-1 rounded-xl p-2 text-sm font-bold ${tab==='chat'?'bg-[#dceceb] text-[#216763]':'hover:bg-[#f1e4cc]'}`}><MessageCircle className="mx-auto" size={18}/></button><button onClick={()=>setTab('groups')} className={`flex-1 rounded-xl p-2 text-sm font-bold ${tab==='groups'?'bg-[#dceceb] text-[#216763]':'hover:bg-[#f1e4cc]'}`}><Users className="mx-auto" size={18}/></button></div>
    <div className="rounded-xl bg-[#f8f2e8] p-3 text-xs text-[#527075]">Direct chat and group conversations are now backed by Supabase. Messages refresh automatically.</div>
    <div className="mt-4 space-y-2"><button onClick={()=>setTab('groups')} className="w-full rounded-xl border border-[#dfd2c0] p-3 text-left text-sm font-bold">Browse groups</button><button onClick={()=>setTab('chat')} className="w-full rounded-xl border border-[#dfd2c0] p-3 text-left text-sm font-bold">Messages</button></div>
   </aside>
   <main className="flex min-w-0 flex-1 flex-col">
    {!selectedGroup?<div className="flex h-full flex-col p-5"><div className="mb-4 flex gap-2 sm:hidden"><button onClick={()=>setTab('chat')} className={`flex-1 rounded-xl p-2 ${tab==='chat'?'bg-[#dceceb]':''}`}>Messages</button><button onClick={()=>setTab('groups')} className={`flex-1 rounded-xl p-2 ${tab==='groups'?'bg-[#dceceb]':''}`}>Groups</button></div>
     {tab==='groups'?<><div className="mb-4 flex gap-2"><div className="flex flex-1 items-center gap-2 rounded-xl border border-[#dfd2c0] bg-[#f8f2e8] px-3"><Search size={17}/><input value={search} onChange={e=>{setSearch(e.target.value);loadGroups(e.target.value).catch(()=>undefined)}} placeholder="Find a group" className="w-full bg-transparent p-2 outline-none"/></div><button onClick={createGroup} disabled={!newGroup.trim()||busy} className="rounded-xl bg-[#2f817d] px-3 text-white"><Plus/></button></div><input value={newGroup} onChange={e=>setNewGroup(e.target.value)} placeholder="New group name" className="mb-4 rounded-xl border border-[#dfd2c0] bg-white p-3 outline-none focus:border-[#2f817d]"/><div className="grid gap-3 sm:grid-cols-2">{groups.map(g=><button key={g.id} onClick={()=>loadGroupMessages(g)} className="rounded-2xl border border-[#dfd2c0] p-4 text-left hover:border-[#2f817d]"><div className="flex items-center gap-3"><div className="rounded-xl bg-[#e8c17a] p-2"><Users size={18}/></div><div><b className="text-[#1d4348]">{g.name}</b><p className="text-xs text-[#789093]">{g.description||'Community group'}</p></div></div></button>)}</div></>:<div className="rounded-2xl border border-dashed border-[#d8c9b3] p-8 text-center"><MessageCircle className="mx-auto mb-3 text-[#2f817d]"/><h3 className="font-extrabold text-[#1d4348]">Direct messages</h3><p className="mt-1 text-sm text-[#70878a]">Use the social API to start conversations with other members. The group chat side is fully active here.</p></div>}
    </div>:<><div className="flex items-center gap-3 border-b border-[#eadfce] p-4"><button onClick={()=>setSelectedGroup(null)} className="rounded-xl p-2 hover:bg-[#f1e4cc]">←</button><div><b className="text-[#1d4348]">{selectedGroup.name}</b><p className="text-xs text-[#789093]">Group chat</p></div></div><div className="flex-1 space-y-3 overflow-y-auto p-4">{messages.map(m=><div key={m.id} className="rounded-2xl bg-[#f1e4cc] p-3 text-sm text-[#365b60]"><div className="mb-1 text-[10px] font-bold uppercase text-[#789093]">{m.sender_id===initials?'You':'Member'} · {new Date(m.created_at).toLocaleString()}</div>{m.body}</div>)}{!messages.length&&<p className="text-center text-sm text-[#789093]">No messages yet. Humanity has briefly achieved silence.</p>}</div><div className="flex gap-2 border-t border-[#eadfce] p-3"><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')send()}} placeholder="Write a message…" className="min-w-0 flex-1 rounded-xl border border-[#dfd2c0] bg-[#f8f2e8] p-3 outline-none focus:border-[#2f817d]"/><button onClick={send} disabled={!text.trim()||busy} className="rounded-xl bg-[#2f817d] p-3 text-white disabled:opacity-50"><Send size={18}/></button></div></>}
   </main></div>
  </div></div>}
 </>;
}
