import { useEffect, useMemo, useRef, useState, type ChangeEvent } from 'react';
import { Bell, Camera, Check, ChevronLeft, Eye, EyeOff, LogOut, MessageCircle, Plus, Search, Send, Settings, UserRound, Users, X } from 'lucide-react';
import { useAuth } from '@/lib/auth';

type Group={id:number;name:string;description?:string|null;created_by:string};
type Person={id:string;full_name?:string|null;username?:string|null;avatar_url?:string|null;bio?:string|null;department?:string|null};
type Chat={id:number;conversation_id?:number|null;group_id?:number|null;sender_id:string;body:string;created_at:string;is_view_once?:boolean};
const api=(path:string,init?:RequestInit)=>fetch(`/api${path}`,{...init,credentials:'include',headers:{'Content-Type':'application/json',...(init?.headers||{})}}).then(async r=>{const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.error||'Request failed');return d});

export function SocialHub(){
 const {user,logout,updateProfile,uploadAvatar}=useAuth();
 const [open,setOpen]=useState(false),[tab,setTab]=useState<'messages'|'people'|'groups'>('messages'),[people,setPeople]=useState<Person[]>([]),[groups,setGroups]=useState<Group[]>([]),[query,setQuery]=useState(''),[selected,setSelected]=useState<Person|null>(null),[group,setGroup]=useState<Group|null>(null),[conversation,setConversation]=useState<number|null>(null),[messages,setMessages]=useState<Chat[]>([]),[text,setText]=useState(''),[busy,setBusy]=useState(false),[settings,setSettings]=useState(false),[name,setName]=useState(''),[bio,setBio]=useState(''),[password,setPassword]=useState(''),[notice,setNotice]=useState(''),[viewOnce,setViewOnce]=useState(false),[newGroup,setNewGroup]=useState('');
 const fileRef=useRef<HTMLInputElement>(null);
 const initials=useMemo(()=>{const n=user?.profile?.full_name||user?.email?.split('@')[0]||'OL';return n.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()},[user]);
 const loadPeople=async(q='')=>{try{setPeople(await api(`/people${q.trim()?`?q=${encodeURIComponent(q.trim())}`:''}`))}catch(e){setNotice(e instanceof Error?e.message:'Could not search members')}};
 const loadGroups=async(q='')=>{try{setGroups(await api(`/groups${q.trim()?`?q=${encodeURIComponent(q.trim())}`:''}`))}catch(e){setNotice(e instanceof Error?e.message:'Could not load groups')}};
 const loadMessages=async()=>{const p=group?`/groups/${group.id}/messages`:conversation?`/conversations/${conversation}/messages`:'';if(p)try{setMessages(await api(p))}catch{}};
 useEffect(()=>{if(open){void loadPeople();void loadGroups()}},[open]);
 useEffect(()=>{if(open&&tab==='people')void loadPeople(query);if(open&&tab==='groups')void loadGroups(query)},[tab]);
 useEffect(()=>{if(!open)return;const t=window.setInterval(()=>void loadMessages(),4000);return()=>window.clearInterval(t)},[open,group,conversation]);
 useEffect(()=>{if(settings){setName(user?.profile?.full_name||'');setBio(user?.profile?.bio||'')}},[settings,user]);
 async function startChat(p:Person){setBusy(true);setNotice('');try{const c=await api('/conversations',{method:'POST',body:JSON.stringify({user_ids:[p.id]})});setSelected(p);setGroup(null);setConversation(c.id);setMessages(await api(`/conversations/${c.id}/messages`));setTab('messages')}catch(e){setNotice(e instanceof Error?e.message:'Could not open chat')}finally{setBusy(false)}}
 async function openGroup(g:Group){setBusy(true);try{await api(`/groups/${g.id}/join`,{method:'POST'});setGroup(g);setSelected(null);setConversation(null);setMessages(await api(`/groups/${g.id}/messages`));setTab('messages')}catch(e){setNotice(e instanceof Error?e.message:'Could not open group')}finally{setBusy(false)}}
 async function createGroup(){if(!newGroup.trim()||busy)return;setBusy(true);try{const g=await api('/groups',{method:'POST',body:JSON.stringify({name:newGroup.trim()})});setGroups(v=>[g,...v]);setNewGroup('');await openGroup(g)}catch(e){setNotice(e instanceof Error?e.message:'Could not create group')}finally{setBusy(false)}}
 async function send(){if(!text.trim()||busy||(!group&&!conversation))return;setBusy(true);try{const path=group?`/groups/${group.id}/messages`:`/conversations/${conversation}/messages`;const m=await api(path,{method:'POST',body:JSON.stringify({body:text.trim(),is_view_once:viewOnce})});setMessages(v=>[...v,(Array.isArray(m)?m[0]:m)]);setText('');setViewOnce(false)}catch(e){setNotice(e instanceof Error?e.message:'Message could not be sent')}finally{setBusy(false)}}
 async function openViewOnce(messageId:number){if(busy)return;setBusy(true);setNotice('');try{await api(`/messages/${messageId}/view-once`,{method:'POST'});setMessages(v=>v.map(m=>m.id===messageId?{...m,is_view_once:false,body:'This view-once message has been opened.'}:m));setNotice('View-once message opened.')}catch(e){setNotice(e instanceof Error?e.message:'Could not open this view-once message')}finally{setBusy(false)}}
 async function save(){setBusy(true);try{await updateProfile({full_name:name.trim()||null,bio:bio.trim()||null});if(password.trim()){if(password.trim().length<8)throw new Error('New password must be at least 8 characters.');await api('/settings/account',{method:'PATCH',body:JSON.stringify({password:password.trim()})});setPassword('')}setNotice('Changes saved')}catch(e){setNotice(e instanceof Error?e.message:'Could not save changes')}finally{setBusy(false)}}
 async function avatar(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;if(f.size>5*1024*1024){setNotice('Profile pictures must be 5 MB or smaller.');return}try{await uploadAvatar(f);setNotice('Profile picture updated')}catch(e){setNotice(e instanceof Error?e.message:'Upload failed')}}
 const back=()=>{setSelected(null);setGroup(null);setConversation(null);setMessages([])};
 return <>
  <button aria-label="Open OLANET Messages" onClick={()=>setOpen(true)} className="fixed bottom-5 right-5 z-30 grid h-14 w-14 place-items-center rounded-full bg-[#1877f2] text-white shadow-xl hover:bg-[#166fe5]"><MessageCircle size={24}/></button>
  {open&&<div className="fixed inset-0 z-50 bg-black/30 p-0 sm:p-5"><div className="mx-auto flex h-full max-w-5xl flex-col overflow-hidden bg-white sm:rounded-xl sm:shadow-2xl">
   <header className="flex h-16 shrink-0 items-center justify-between border-b border-[#dddfe2] bg-white px-4"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-full bg-[#1877f2] font-bold text-white">O</div><div><h2 className="text-lg font-bold text-[#1c1e21]">OLANET</h2><p className="text-xs text-[#65676b]">Connect with people and communities</p></div></div><div className="flex gap-1"><button onClick={()=>setSettings(true)} aria-label="Settings" className="grid h-10 w-10 place-items-center rounded-full bg-[#f0f2f5] hover:bg-[#e4e6eb]"><Settings size={19}/></button><button onClick={()=>setOpen(false)} aria-label="Close" className="grid h-10 w-10 place-items-center rounded-full bg-[#f0f2f5] hover:bg-[#e4e6eb]"><X size={20}/></button></div></header>
   <div className="flex min-h-0 flex-1">
    <aside className="hidden w-64 shrink-0 border-r border-[#dddfe2] bg-white p-3 sm:block"><nav className="space-y-1"><button onClick={()=>{back();setTab('messages')}} className={`flex w-full items-center gap-3 rounded-lg p-3 text-left text-sm font-bold ${tab==='messages'?'bg-[#e7f3ff] text-[#1877f2]':'hover:bg-[#f0f2f5]'}`}><MessageCircle size={19}/> Messages</button><button onClick={()=>{back();setTab('people');void loadPeople(query)}} className={`flex w-full items-center gap-3 rounded-lg p-3 text-left text-sm font-bold ${tab==='people'?'bg-[#e7f3ff] text-[#1877f2]':'hover:bg-[#f0f2f5]'}`}><Users size={19}/> Find people</button><button onClick={()=>{back();setTab('groups');void loadGroups(query)}} className={`flex w-full items-center gap-3 rounded-lg p-3 text-left text-sm font-bold ${tab==='groups'?'bg-[#e7f3ff] text-[#1877f2]':'hover:bg-[#f0f2f5]'}`}><UserRound size={19}/> Groups</button><button onClick={()=>setSettings(true)} className="flex w-full items-center gap-3 rounded-lg p-3 text-left text-sm font-bold hover:bg-[#f0f2f5]"><Settings size={19}/> Settings</button></nav><div className="mt-5 border-t border-[#dddfe2] pt-3"><p className="px-3 py-2 text-xs font-bold text-[#65676b]">Signed in as</p><div className="flex items-center gap-2 px-3"><div className="grid h-9 w-9 place-items-center rounded-full bg-[#d8eaff] font-bold">{initials}</div><span className="truncate text-sm font-bold">{user?.profile?.full_name||user?.email}</span></div></div></aside>
    <main className="flex min-w-0 flex-1 flex-col">
     <div className="flex border-b border-[#dddfe2] bg-white sm:hidden"><button onClick={()=>{back();setTab('messages')}} className="flex-1 p-3 text-xs font-bold">Messages</button><button onClick={()=>{back();setTab('people');void loadPeople(query)}} className="flex-1 p-3 text-xs font-bold">People</button><button onClick={()=>{back();setTab('groups');void loadGroups(query)}} className="flex-1 p-3 text-xs font-bold">Groups</button></div>
     {!selected&&!group&&!conversation?<div className="flex h-full flex-col p-4 sm:p-6">
      {tab!=='messages'&&<div className="mb-4 flex gap-2"><div className="flex min-w-0 flex-1 items-center gap-2 rounded-full bg-[#f0f2f5] px-4"><Search size={18} className="text-[#65676b]"/><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')tab==='people'?void loadPeople(query):void loadGroups(query)}} placeholder={tab==='people'?'Search any OLANET user by name or username':'Search groups'} className="min-w-0 flex-1 bg-transparent py-3 outline-none"/></div><button onClick={()=>tab==='people'?void loadPeople(query):void loadGroups(query)} className="rounded-full bg-[#1877f2] px-5 font-bold text-white hover:bg-[#166fe5]" aria-label="Search">Search</button></div>}
      {tab==='messages'&&<div className="rounded-xl bg-[#f0f2f5] p-8 text-center"><MessageCircle className="mx-auto mb-3 text-[#1877f2]"/><h3 className="text-lg font-bold">Your messages</h3><p className="mx-auto mt-1 max-w-md text-sm text-[#65676b]">Find any registered OLANET user and open a private one-to-one chat. Individual users do not have AI.</p><button onClick={()=>{setTab('people');void loadPeople()}} className="mt-4 rounded-lg bg-[#1877f2] px-5 py-2.5 text-sm font-bold text-white">Find people</button></div>}
      {tab==='people'&&<div className="space-y-1 overflow-auto">{people.map(p=><button key={p.id} onClick={()=>void startChat(p)} className="flex w-full items-center gap-3 rounded-lg p-3 text-left hover:bg-[#f0f2f5]">{p.avatar_url?<img src={p.avatar_url} alt="" className="h-12 w-12 rounded-full object-cover"/>:<div className="grid h-12 w-12 place-items-center rounded-full bg-[#d8eaff] font-bold">{(p.full_name||p.username||'OL').slice(0,2).toUpperCase()}</div>}<div className="min-w-0"><p className="font-bold text-[#1c1e21]">{p.full_name||p.username||'OLANET user'}</p><p className="truncate text-xs text-[#65676b]">@{p.username||'member'} {p.bio?'· '+p.bio:''}</p></div></button>)}{!people.length&&<p className="p-6 text-center text-sm text-[#65676b]">No matching OLANET users found.</p>}</div>}
      {tab==='groups'&&<><div className="mb-4 flex gap-2"><input value={newGroup} onChange={e=>setNewGroup(e.target.value)} placeholder="Create a new group" className="min-w-0 flex-1 rounded-lg border p-3"/><button onClick={()=>void createGroup()} disabled={!newGroup.trim()||busy} className="grid h-11 w-11 place-items-center rounded-lg bg-[#1877f2] text-white disabled:opacity-50"><Plus size={20}/></button></div><div className="space-y-2 overflow-auto">{groups.map(g=><div key={g.id} className="rounded-xl border border-[#dddfe2] p-4"><p className="font-bold">{g.name}</p><p className="text-sm text-[#65676b]">{g.description||'OLANET community group'}</p><button onClick={()=>void openGroup(g)} className="mt-3 rounded-lg bg-[#e7f3ff] px-4 py-2 text-sm font-bold text-[#1877f2]">Open group</button></div>)}</div></>}
     </div>:<div className="flex min-h-0 flex-1 flex-col"><header className="flex items-center gap-3 border-b border-[#dddfe2] p-3"><button onClick={back} className="grid h-9 w-9 place-items-center rounded-full bg-[#f0f2f5]"><ChevronLeft size={20}/></button>{selected?.avatar_url?<img src={selected.avatar_url} alt="" className="h-10 w-10 rounded-full object-cover"/>:<div className="grid h-10 w-10 place-items-center rounded-full bg-[#d8eaff] font-bold">{(selected?.full_name||group?.name||'OL').slice(0,2).toUpperCase()}</div>}<div><p className="font-bold">{selected?.full_name||group?.name||'Chat'}</p><p className="text-xs text-[#65676b]">{selected?'Private chat':'Group conversation'}</p></div></header><div className="flex-1 space-y-2 overflow-y-auto bg-[#f0f2f5] p-4">{messages.map(m=><div key={m.id} className={`max-w-[80%] rounded-2xl px-3 py-2 text-sm ${m.sender_id===user?.id?'ml-auto bg-[#1877f2] text-white':'bg-white text-[#1c1e21]'}`}>{m.is_view_once&&m.sender_id!==user?.id?<button onClick={()=>void openViewOnce(m.id)} disabled={busy} className="font-bold disabled:opacity-50"><Eye size={15} className="mr-1 inline"/>View once</button>:m.body}</div>)}{!messages.length&&<p className="text-center text-sm text-[#65676b]">No messages yet.</p>}</div><div className="border-t border-[#dddfe2] bg-white p-3"><div className="mb-2 flex items-center gap-2"><button onClick={()=>setViewOnce(v=>!v)} className={`rounded-full px-3 py-1 text-xs font-bold ${viewOnce?'bg-[#e7f3ff] text-[#1877f2]':'bg-[#f0f2f5] text-[#65676b]'}`}><EyeOff size={13} className="mr-1 inline"/>{viewOnce?'View once ON':'View once'}</button></div><div className="flex gap-2"><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void send()}} placeholder="Write a message…" className="min-w-0 flex-1 rounded-full bg-[#f0f2f5] px-4 py-3 outline-none"/><button onClick={()=>void send()} disabled={!text.trim()||busy} className="grid h-11 w-11 place-items-center rounded-full bg-[#1877f2] text-white disabled:opacity-50"><Send size={18}/></button></div></div></div>}
    </main>
   </div>
  </div></div>}
  {settings&&<div className="fixed inset-0 z-[70] bg-black/35"><div className="ml-auto flex h-full w-full max-w-md flex-col bg-white"><header className="flex items-center justify-between border-b p-4"><div><p className="text-xs font-bold text-[#1877f2]">OLANET</p><h2 className="text-xl font-bold">Settings</h2></div><button onClick={()=>setSettings(false)} className="grid h-9 w-9 place-items-center rounded-full bg-[#f0f2f5]"><X size={19}/></button></header><div className="flex-1 overflow-y-auto p-5"><div className="mb-6 flex items-center gap-3"><button onClick={()=>fileRef.current?.click()} className="relative"><div className="grid h-20 w-20 place-items-center overflow-hidden rounded-full bg-[#d8eaff] text-xl font-bold">{user?.profile?.avatar_url?<img src={user.profile.avatar_url} alt="" className="h-full w-full object-cover"/>:initials}</div><span className="absolute bottom-0 right-0 rounded-full bg-[#1877f2] p-2 text-white"><Camera size={14}/></span></button><input ref={fileRef} type="file" accept="image/*" className="hidden" onChange={avatar}/><div><p className="font-bold">{user?.profile?.full_name||'OLANET member'}</p><p className="text-xs text-[#65676b]">{user?.email}</p></div></div><label className="mb-4 block text-sm font-bold">Name<input value={name} onChange={e=>setName(e.target.value)} className="mt-1 w-full rounded-lg border p-3 font-normal"/></label><label className="mb-4 block text-sm font-bold">Bio<textarea value={bio} onChange={e=>setBio(e.target.value)} className="mt-1 h-24 w-full rounded-lg border p-3 font-normal"/></label><label className="mb-4 block text-sm font-bold">New password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-1 w-full rounded-lg border p-3 font-normal" placeholder="At least 8 characters"/></label><button onClick={()=>void save()} disabled={busy} className="w-full rounded-lg bg-[#1877f2] p-3 font-bold text-white disabled:opacity-50">{busy?'Saving…':'Save changes'}</button>{notice&&<p className="mt-3 rounded-lg bg-[#e7f3ff] p-3 text-sm font-bold text-[#1877f2]">{notice}</p>}<div className="mt-6 border-t pt-5"><div className="mb-2 flex items-center gap-2 text-sm font-bold"><Bell size={17}/> Notifications</div><div className="flex items-center gap-2 rounded-lg bg-[#f0f2f5] p-3 text-sm"><Check size={16}/> Notifications are enabled</div></div></div><div className="border-t p-5"><button onClick={()=>void logout()} className="flex w-full items-center gap-3 rounded-lg bg-[#ffebe7] p-3 font-bold text-[#e41e3f]"><LogOut size={18}/> Log out</button></div></div></div>}
 </>;
}
