const ACCESS_COOKIE="skillhub_access_token";
const REFRESH_COOKIE="skillhub_refresh_token";
function config(){const url=String(process.env.SUPABASE_URL||"").trim().replace(/\/$/,"");const key=String(process.env.SUPABASE_SERVICE_ROLE_KEY||process.env.SUPABASE_ANON_KEY||"").trim();if(!url||!key)throw new Error("Supabase environment is not configured");return{url,key};}
async function sb(path,options={}){const{url,key}=config();return fetch(`${url}${path}`,{...options,headers:{apikey:key,"Content-Type":"application/json",...(options.headers||{})}});}
async function json(r){const t=await r.text();if(!t)return null;try{return JSON.parse(t)}catch{return null}}
function cookies(req){const out={};for(const part of String(req.headers.cookie||"").split(";")){const i=part.indexOf("=");if(i>0)out[part.slice(0,i).trim()]=decodeURIComponent(part.slice(i+1).trim())}return out}
function setSession(res,d){res.setHeader("Set-Cookie",[`${ACCESS_COOKIE}=${encodeURIComponent(d.access_token)}; Path=/; HttpOnly; SameSite=Lax; Max-Age=3600; Secure`,`${REFRESH_COOKIE}=${encodeURIComponent(d.refresh_token)}; Path=/; HttpOnly; SameSite=Lax; Max-Age=2592000; Secure`])}
async function session(req,res){const c=cookies(req);let token=c[ACCESS_COOKIE],user=null;if(token){const r=await sb("/auth/v1/user",{headers:{Authorization:`Bearer ${token}`}});if(r.ok)user=await json(r)}if(!user&&c[REFRESH_COOKIE]){const r=await sb("/auth/v1/token?grant_type=refresh_token",{method:"POST",body:JSON.stringify({refresh_token:c[REFRESH_COOKIE]})});const d=await json(r);if(r.ok&&d?.access_token&&d?.user){token=d.access_token;user=d.user;setSession(res,d)}}if(!user?.id){res.status(401).json({error:"Not authenticated. Please log in again."});return null}return{user,token}}
export default async function handler(req,res){if(req.method!=="POST")return res.status(405).json({error:"Method not allowed."});try{const s=await session(req,res);if(!s)return;const ids=[...new Set((Array.isArray(req.body?.user_ids)?req.body.user_ids:[]).filter(x=>typeof x==="string"&&x!==s.user.id))];if(ids.length!==1)return res.status(400).json({error:"A private chat must contain exactly one other user."});const other=ids[0];const target=await sb(`/rest/v1/profiles?select=id&id=eq.${encodeURIComponent(other)}&limit=1`);const targetRows=await json(target);if(!target.ok)return res.status(target.status).json({error:"Could not verify that OLANET user.",details:targetRows});if(!Array.isArray(targetRows)||!targetRows.length)return res.status(404).json({error:"That OLANET user no longer exists."});
const mine=await sb(`/rest/v1/direct_conversation_members?user_id=eq.${encodeURIComponent(s.user.id)}&select=conversation_id&limit=1000`,{headers:{Authorization:`Bearer ${s.token}`}});const mineRows=await json(mine)||[];const idsList=mineRows.map(x=>x.conversation_id).filter(Number.isInteger);if(idsList.length){const targetRows2=await sb(`/rest/v1/direct_conversation_members?user_id=eq.${encodeURIComponent(other)}&conversation_id=in.(${idsList.join(",")})&select=conversation_id&limit=1000`,{headers:{Authorization:`Bearer ${s.token}`}});const shared=await json(targetRows2)||[];const sharedIds=shared.map(x=>x.conversation_id).filter(Number.isInteger);if(sharedIds.length){const existing=await sb(`/rest/v1/direct_conversations?id=in.(${sharedIds.join(",")})&select=*&order=created_at.desc&limit=1`,{headers:{Authorization:`Bearer ${s.token}`}});const rows=await json(existing);if(existing.ok&&Array.isArray(rows)&&rows[0])return res.status(200).json(rows[0]);}}
const c=await sb("/rest/v1/direct_conversations?select=*",{method:"POST",headers:{Authorization:`Bearer ${s.token}`,Prefer:"return=representation"},body:"{}"});const cd=await json(c);const conversation=Array.isArray(cd)?cd[0]:cd;if(!c.ok||!conversation?.id)return res.status(c.status||502).json(cd||{error:"Could not create conversation."});const mr=await sb("/rest/v1/direct_conversation_members",{method:"POST",headers:{Authorization:`Bearer ${s.token}`},body:JSON.stringify([{conversation_id:conversation.id,user_id:s.user.id},{conversation_id:conversation.id,user_id:other}])});const md=await json(mr);if(!mr.ok)return res.status(mr.status||502).json({error:"Could not add conversation members.",details:md});return res.status(201).json(conversation);}catch(e){return res.status(500).json({error:e?.message||"Could not open conversation."})}}
